In [1]:
import pandas as pd
import numpy as np

drought = pd.read_csv("Drought_clean.csv")
earthquake = pd.read_csv("Earthquake_clean.csv")
eruption = pd.read_csv("Eruption_clean.csv")
flood = pd.read_csv("Flood_clean.csv")
forest_fires = pd.read_csv("Forest_Fires_clean.csv")
tropical_cyclone = pd.read_csv("Tropical_Cyclone_clean.csv")

In [2]:
print(drought.shape)
print(earthquake.shape)
print(eruption.shape)
print(flood.shape)
print(forest_fires.shape)
print(tropical_cyclone.shape)

(240, 14)
(20290, 16)
(61, 18)
(2126, 17)
(3051, 14)
(405, 20)

In [3]:
print(drought.columns)
print(earthquake.columns)
print(eruption.columns)
print(flood.columns)
print(forest_fires.columns)
print(tropical_cyclone.columns)

Index(['Description', 'Alertlevel', 'Alertscore', 'Episodealertscore',
       'Country', 'Fromdate', 'Todate', 'Severity (km2)', 'Iso3', 'Gdacs id',
       'Duration (days)', 'Impact', 'Longitude', 'Latitude'],
      dtype='str')
Index(['description', 'alertlevel', 'alertscore', 'episodealertlevel',
       'episodealertscore', 'country', 'fromdate', 'todate', 'source', 'iso3',
       'Earthquake Magnitude (M)', 'Capacity', 'Depth (km)', 'longitude',
       'latitude', 'Exposed Population (within 100 km)'],
      dtype='str')
Index(['description', 'alertlevel', 'alertscore', 'episodealertlevel',
       'episodealertscore', 'country', 'fromdate', 'todate', 'severity',
       'source', 'iso3', 'GDACS ID', 'Exposed Population 30km',
       'Exposed Population 100km', 'Max Volc. Explosivity Index VEI',
       'Population Exposure Index PEI', 'longitude', 'latitude'],
      dtype='str')
Index(['Unnamed: 0', 'description', 'alertlevel', 'alertscore',
       'episodealertlevel', 'episodealertscore', 'country', 'fromdate',
       'todate', 'severity (magnitude)', 'source', 'iso3', 'Death',
       'Displaced', 'GDACS_ID', 'longitude', 'latitude'],
      dtype='str')
Index(['description', 'alertlevel', 'alertscore', 'episodealertscore',
       'country', 'fromdate', 'todate', 'severity (ha)', 'iso3', 'GDACS ID',
       'People affected', 'Duration (days)', 'longitude', 'latitude'],
      dtype='str')
Index(['description', 'alertlevel', 'alertscore', 'episodealertlevel',
       'episodealertscore', 'fromdate', 'todate', 'severity', 'severitytext',
       'source', 'iso3', 'GDACS ID', 'Exposed countries', 'Exposed population',
       'Maximum wind speed (km/h)', 'Maximum storm surge (m)', 'Vulnerability',
       'longitude', 'latitude', 'Category'],
      dtype='str')

In [4]:
print("Drought:")
display(drought.head())

print("Earthquake:")
display(earthquake.head())

print("Eruption:")
display(eruption.head())

print("Flood:")
display(flood.head())

print("Forest Fires:")
display(forest_fires.head())

print("Tropical Cyclone:")
display(tropical_cyclone.head())

Drought:

,Description,Alertlevel,Alertscore,Episodealertscore,Country,Fromdate,Todate,Severity (km2),Iso3,Gdacs id,Duration (days),Impact,Longitude,Latitude
0,"Green Drought in Germany, Denmark, France, Lat...",Green,1.0,0.25,"Germany, Denmark, France, Latvia, Poland, Sweden",2017-07-21,2019-02-09 15:07:00,80936.0,DEU,DR 1012168,569.0,Minor impact for agricultural drought in 80936...,11.087,53.882
1,Green Drought in Uzbekistan from: 21 Nov 2017 ...,Green,1.0,0.75,Uzbekistan,2017-11-21,2018-09-06 09:57:00,18686.0,UZB,DR 1012172,289.0,Minor impact for agricultural drought in 18686...,65.500,40.996
2,Green Drought in Brazil from: 21 Dec 2017 to:...,Green,1.0,0.50,Brazil,2017-12-21,2018-09-06 09:57:00,87604.0,BRA,DR 1012174,259.0,Minor impact for agricultural drought in 87604...,-50.105,-21.917
3,Orange Drought in Australia from: 21 Feb 2018 ...,Orange,2.0,1.00,Australia,2018-02-21,2018-11-24 16:27:00,142608.0,AUS,DR 1012191,277.0,Medium impact for agricultural drought in 1426...,144.500,-33.500
4,Orange Drought in Madagascar from: 21 Mar 2018...,Orange,2.0,1.50,Madagascar,2018-03-21,2018-09-13 13:57:00,68692.0,MDG,DR 1012304,177.0,Medium impact for agricultural drought in 6869...,46.464,-19.498

Earthquake:

,description,alertlevel,alertscore,episodealertlevel,episodealertscore,country,fromdate,todate,source,iso3,Earthquake Magnitude (M),Capacity,Depth (km),longitude,latitude,Exposed Population (within 100 km)
0,Red M 6.4 Earthquake in Afghanistan at: 19 Jan...,Red,3.0,Red,3.0,Afghanistan,2000-01-19 00:00:00,2000-01-19 00:00:00,NEIC,AFG,6.4,-1,0.0,70.400,36.200,460000.0
1,Green M 4.9 Earthquake in Iran at: 14 Feb 2000...,Green,1.0,Green,0.5,Iran,2000-02-14 00:00:00,2000-02-14 00:00:00,NEIC,IRN,4.9,-1,0.0,58.175,35.217,440000.0
2,Green M 5.3 Earthquake in Iran at: 03 Feb 2000...,Green,1.0,Green,0.5,Iran,2000-02-03 00:00:00,2000-02-03 00:00:00,NEIC,IRN,5.3,-1,0.0,58.218,35.288,470000.0
3,"Green M 5.5 Earthquake in Crete, Greece at: 05...",Green,1.0,Green,0.0,"Crete, Greece",2000-04-05 04:37:00,2000-04-05 04:37:00,NGDC,NaN,5.5,1.1 (),10.0,25.690,34.220,30000.0
4,Orange M 7.6 Earthquake in Indonesia at: 04 Ma...,Orange,2.0,Orange,1.5,Indonesia,2000-05-04 04:21:00,2000-05-04 04:21:00,NGDC,IDN,7.6,4.8 (Indonesia),10.0,123.573,-1.105,90000.0

Eruption:

,description,alertlevel,alertscore,episodealertlevel,episodealertscore,country,fromdate,todate,severity,source,iso3,GDACS ID,Exposed Population 30km,Exposed Population 100km,Max Volc. Explosivity Index VEI,Population Exposure Index PEI,longitude,latitude
0,Green Eruption Iskut-Unuk River Cones in Canad...,Green,1.0,Green,0.0,Canada,2011-09-20 18:00:00,2011-09-20 18:00:00,0.0,MONTREAL,-1,VO 360,-1.0,0.0,-1.0,-1.0,-130.550000,56.583333
1,"Green Eruption Hudson, Cerro in Chile-S at: 28...",Green,1.0,Green,0.0,Chile-S,2011-10-28 09:48:00,2011-10-28 09:48:00,0.0,BUENOS AIRES,-1,VO 484,-1.0,0.0,-1.0,-1.0,-72.966666,-45.900000
2,Green Eruption Yasur in Vanuatu-SW Pacific at:...,Green,1.0,Green,0.0,Vanuatu-SW Pacific,2011-12-30 18:00:00,2011-12-30 18:00:00,0.0,WELLINGTON,-1,VO 103,-1.0,0.0,-1.0,-1.0,169.441666,-19.533333
3,Green Eruption Pagan in Mariana Is-C Pacific a...,Green,1.0,Green,0.0,Mariana Is-C Pacific,2012-01-30 07:31:00,2012-01-30 07:31:00,0.0,WASHINGTON,-1,VO 253,-1.0,0.0,-1.0,-1.0,145.800000,18.133333
4,Orange Eruption Dukono in Halmahera-Indonesia ...,Orange,2.0,Orange,2.0,Halmahera-Indonesia,2012-02-28 04:30:00,2012-02-28 04:30:00,0.0,DARWIN,-1,VO 178,-1.0,0.0,-1.0,-1.0,127.883333,1.683333

Flood:

,Unnamed: 0,description,alertlevel,alertscore,episodealertlevel,episodealertscore,country,fromdate,todate,severity (magnitude),source,iso3,Death,Displaced,GDACS_ID,longitude,latitude
0,0,ORANGE Flood in Mozambique from: 26 Jan 2000 0...,ORANGE,2.0,ORANGE,2.0,Mozambique,2000-01-26 00:00:00,2000-03-27 23:59:59,7.74,DFO,MOZ,929.0,733000.0,FL 1583,31.712,-27.822
1,1,GREEN Flood in Philippines from: 28 Jan 2000 0...,GREEN,1.0,GREEN,1.0,Philippines,2000-01-28 00:00:00,2000-02-01 23:59:59,4.92,DFO,PHL,23.0,20000.0,FL 1584,126.100,7.199
2,2,GREEN Flood in Angola from: 08 Jan 2000 00 to:...,GREEN,1.0,GREEN,1.0,Angola,2000-01-08 00:00:00,2000-01-15 23:59:59,5.58,DFO,AGO,31.0,70000.0,FL 1582,13.246,-14.145
3,3,ORANGE Flood in Southeastern Brazil from: 01 J...,ORANGE,2.0,Orange,2.0,Southeastern Brazil,2000-01-01 00:00:00,2000-01-01 00:00:00,6.55,DFO,,40.0,100000.0,FL 1581,-49.304,-24.891
4,4,RED Flood in Madagascar from: 17 Feb 2000 00 t...,RED,3.0,RED,3.0,Madagascar,2000-02-17 00:00:00,2000-03-11 23:59:59,6.79,DFO,MDG,200.0,800000.0,FL 1587,47.296,-15.783

Forest Fires:

,description,alertlevel,alertscore,episodealertscore,country,fromdate,todate,severity (ha),iso3,GDACS ID,People affected,Duration (days),longitude,latitude
0,Green Forest fires in Laos from: 23 Feb 2021 t...,Green,1.0,1.0,Laos,2021-02-23,2021-03-23,5070.0,LAO,WF 1000144,0.0,28.0,105.659937,17.335162
1,Green Forest fires in India from: 25 Feb 2021 ...,Green,1.0,1.0,India,2021-02-25,2021-03-11,9866.0,IND,WF 1000128,35445.0,14.0,85.875408,22.856787
2,Green Forest fires in Argentina from: 25 Feb 2...,Green,1.0,1.0,Argentina,2021-02-25,2021-03-08,5326.0,ARG,WF 1000127,0.0,11.0,-71.362698,-43.813590
3,Green Forest fires in Myanmar from: 23 Feb 202...,Green,1.0,1.0,Myanmar,2021-02-23,2021-03-08,5353.0,MMR,WF 1000143,0.0,13.0,97.226779,22.268084
4,Green Forest fires in India from: 23 Feb 2021 ...,Green,1.0,1.0,India,2021-02-23,2021-03-07,7572.0,IND,WF 1000142,8550.0,12.0,82.750550,20.166615

Tropical Cyclone:

,description,alertlevel,alertscore,episodealertlevel,episodealertscore,fromdate,todate,severity,severitytext,source,iso3,GDACS ID,Exposed countries,Exposed population,Maximum wind speed (km/h),Maximum storm surge (m),Vulnerability,longitude,latitude,Category
0,Red Tropical Cyclone NARGIS-08 off-shore from:...,Red,3.0,Green,1.0,2008-04-28 06:00:00,2008-05-03 12:00:00,74.029824,Tropical Storm (maximum wind speed of 212 km/h),JTWC,,TC 10238,Off-shore,7000000.0,74.0,-1.0,-1,97.5,18.299999,-1.0
1,Orange Tropical Cyclone SONGDA-11 in Japan fro...,Orange,2.0,Green,1.0,2011-05-22 00:00:00,2011-05-29 12:00:00,64.373760,Tropical Depression (maximum wind speed of 259...,JRC,,TC 24054,Japan,0.0,64.0,-1.0,Low,136.6,34.400000,-1.0
2,Green Tropical Cyclone MUIFA-11 in Japan from:...,Green,1.0,Green,1.0,2011-07-28 06:00:00,2011-08-08 12:00:00,286.463232,Tropical Storm (maximum wind speed of 259 km/h),JRC,,TC 25110,Japan,1200000.0,286.0,-1.0,Low,124.9,40.300000,5.0
3,Green Tropical Cyclone EUGENE-11 off-shore fro...,Green,1.0,Green,1.0,2011-07-31 15:00:00,2011-08-06 09:00:00,222.089472,Tropical Storm (maximum wind speed of 222 km/h),JRC,,TC 25192,Off-shore,0.0,222.0,-1.0,-1,-127.1,18.900000,4.0
4,Green Tropical Cyclone NOCK-TEN-11 in Philippi...,Green,1.0,Green,1.0,2011-07-26 00:00:00,2011-07-30 12:00:00,120.700800,Tropical Storm (maximum wind speed of 120 km/h),JRC,,TC 25101,"Philippines,China,Vietnam",0.0,121.0,-1.0,High,105.5,19.100000,1.0

In [5]:
print("Drought:", drought.columns.tolist())
print("Earthquake:", earthquake.columns.tolist())
print("Eruption:", eruption.columns.tolist())
print("Flood:", flood.columns.tolist())
print("Forest Fires:", forest_fires.columns.tolist())
print("Tropical Cyclone:", tropical_cyclone.columns.tolist())

Drought: ['Description', 'Alertlevel', 'Alertscore', 'Episodealertscore', 'Country', 'Fromdate', 'Todate', 'Severity (km2)', 'Iso3', 'Gdacs id', 'Duration (days)', 'Impact', 'Longitude', 'Latitude']
Earthquake: ['description', 'alertlevel', 'alertscore', 'episodealertlevel', 'episodealertscore', 'country', 'fromdate', 'todate', 'source', 'iso3', 'Earthquake Magnitude (M)', 'Capacity', 'Depth (km)', 'longitude', 'latitude', 'Exposed Population (within 100 km)']
Eruption: ['description', 'alertlevel', 'alertscore', 'episodealertlevel', 'episodealertscore', 'country', 'fromdate', 'todate', 'severity', 'source', 'iso3', 'GDACS ID', 'Exposed Population 30km', 'Exposed Population 100km', 'Max Volc. Explosivity Index VEI', 'Population Exposure Index PEI', 'longitude', 'latitude']
Flood: ['Unnamed: 0', 'description', 'alertlevel', 'alertscore', 'episodealertlevel', 'episodealertscore', 'country', 'fromdate', 'todate', 'severity (magnitude)', 'source', 'iso3', 'Death', 'Displaced', 'GDACS_ID', 'longitude', 'latitude']
Forest Fires: ['description', 'alertlevel', 'alertscore', 'episodealertscore', 'country', 'fromdate', 'todate', 'severity (ha)', 'iso3', 'GDACS ID', 'People affected', 'Duration (days)', 'longitude', 'latitude']
Tropical Cyclone: ['description', 'alertlevel', 'alertscore', 'episodealertlevel', 'episodealertscore', 'fromdate', 'todate', 'severity', 'severitytext', 'source', 'iso3', 'GDACS ID', 'Exposed countries', 'Exposed population', 'Maximum wind speed (km/h)', 'Maximum storm surge (m)', 'Vulnerability', 'longitude', 'latitude', 'Category']

In [6]:
print("Drought:", drought.shape)
print("Earthquake:", earthquake.shape)
print("Eruption:", eruption.shape)
print("Flood:", flood.shape)
print("Forest Fires:", forest_fires.shape)
print("Tropical Cyclone:", tropical_cyclone.shape)

Drought: (240, 14)
Earthquake: (20290, 16)
Eruption: (61, 18)
Flood: (2126, 17)
Forest Fires: (3051, 14)
Tropical Cyclone: (405, 20)

In [7]:
print("Drought:", drought.columns.tolist())
print("Earthquake:", earthquake.columns.tolist())
print("Eruption:", eruption.columns.tolist())
print("Flood:", flood.columns.tolist())
print("Forest Fires:", forest_fires.columns.tolist())
print("Tropical Cyclone:", tropical_cyclone.columns.tolist())

Drought: ['Description', 'Alertlevel', 'Alertscore', 'Episodealertscore', 'Country', 'Fromdate', 'Todate', 'Severity (km2)', 'Iso3', 'Gdacs id', 'Duration (days)', 'Impact', 'Longitude', 'Latitude']
Earthquake: ['description', 'alertlevel', 'alertscore', 'episodealertlevel', 'episodealertscore', 'country', 'fromdate', 'todate', 'source', 'iso3', 'Earthquake Magnitude (M)', 'Capacity', 'Depth (km)', 'longitude', 'latitude', 'Exposed Population (within 100 km)']
Eruption: ['description', 'alertlevel', 'alertscore', 'episodealertlevel', 'episodealertscore', 'country', 'fromdate', 'todate', 'severity', 'source', 'iso3', 'GDACS ID', 'Exposed Population 30km', 'Exposed Population 100km', 'Max Volc. Explosivity Index VEI', 'Population Exposure Index PEI', 'longitude', 'latitude']
Flood: ['Unnamed: 0', 'description', 'alertlevel', 'alertscore', 'episodealertlevel', 'episodealertscore', 'country', 'fromdate', 'todate', 'severity (magnitude)', 'source', 'iso3', 'Death', 'Displaced', 'GDACS_ID', 'longitude', 'latitude']
Forest Fires: ['description', 'alertlevel', 'alertscore', 'episodealertscore', 'country', 'fromdate', 'todate', 'severity (ha)', 'iso3', 'GDACS ID', 'People affected', 'Duration (days)', 'longitude', 'latitude']
Tropical Cyclone: ['description', 'alertlevel', 'alertscore', 'episodealertlevel', 'episodealertscore', 'fromdate', 'todate', 'severity', 'severitytext', 'source', 'iso3', 'GDACS ID', 'Exposed countries', 'Exposed population', 'Maximum wind speed (km/h)', 'Maximum storm surge (m)', 'Vulnerability', 'longitude', 'latitude', 'Category']

In [8]:
for name, df in {
    "Drought": drought,
    "Earthquake": earthquake,
    "Eruption": eruption,
    "Flood": flood,
    "Forest Fires": forest_fires,
    "Tropical Cyclone": tropical_cyclone
}.items():
    print(f"\n{name}")
    for col in df.columns:
        print(" -", col)

Drought
 - Description
 - Alertlevel
 - Alertscore
 - Episodealertscore
 - Country
 - Fromdate
 - Todate
 - Severity (km2)
 - Iso3
 - Gdacs id
 - Duration (days)
 - Impact
 - Longitude
 - Latitude

Earthquake
 - description
 - alertlevel
 - alertscore
 - episodealertlevel
 - episodealertscore
 - country
 - fromdate
 - todate
 - source
 - iso3
 - Earthquake Magnitude (M)
 - Capacity
 - Depth (km)
 - longitude
 - latitude
 - Exposed Population (within 100 km)

Eruption
 - description
 - alertlevel
 - alertscore
 - episodealertlevel
 - episodealertscore
 - country
 - fromdate
 - todate
 - severity
 - source
 - iso3
 - GDACS ID
 - Exposed Population 30km
 - Exposed Population 100km
 - Max Volc. Explosivity Index VEI
 - Population Exposure Index PEI
 - longitude
 - latitude

Flood
 - Unnamed: 0
 - description
 - alertlevel
 - alertscore
 - episodealertlevel
 - episodealertscore
 - country
 - fromdate
 - todate
 - severity (magnitude)
 - source
 - iso3
 - Death
 - Displaced
 - GDACS_ID
 - longitude
 - latitude

Forest Fires
 - description
 - alertlevel
 - alertscore
 - episodealertscore
 - country
 - fromdate
 - todate
 - severity (ha)
 - iso3
 - GDACS ID
 - People affected
 - Duration (days)
 - longitude
 - latitude

Tropical Cyclone
 - description
 - alertlevel
 - alertscore
 - episodealertlevel
 - episodealertscore
 - fromdate
 - todate
 - severity
 - severitytext
 - source
 - iso3
 - GDACS ID
 - Exposed countries
 - Exposed population
 - Maximum wind speed (km/h)
 - Maximum storm surge (m)
 - Vulnerability
 - longitude
 - latitude
 - Category

In [9]:
drought["disaster_type"] = "Drought"
earthquake["disaster_type"] = "Earthquake"
eruption["disaster_type"] = "Eruption"
flood["disaster_type"] = "Flood"
forest_fires["disaster_type"] = "Forest Fire"
tropical_cyclone["disaster_type"] = "Tropical Cyclone"

In [10]:
def standardize_columns(df):
    df = df.copy()
    df.columns = df.columns.str.strip()

    rename_map = {
        "Description": "description",
        "Alertlevel": "alertlevel",
        "Alertscore": "alertscore",
        "Episodealertlevel": "episodealertlevel",
        "Episodealertscore": "episodealertscore",
        "Country": "country",
        "Fromdate": "fromdate",
        "Todate": "todate",
        "Iso3": "iso3",
        "Gdacs id": "gdacs_id",
        "GDACS ID": "gdacs_id",
        "GDACS_ID": "gdacs_id",
        "Longitude": "longitude",
        "Latitude": "latitude"
    }

    df = df.rename(columns=rename_map)

    return df

In [11]:
drought = standardize_columns(drought)
earthquake = standardize_columns(earthquake)
eruption = standardize_columns(eruption)
flood = standardize_columns(flood)
forest_fires = standardize_columns(forest_fires)
tropical_cyclone = standardize_columns(tropical_cyclone)

In [12]:
if "Unnamed: 0" in flood.columns:
    flood = flood.drop(columns=["Unnamed: 0"])

print(flood.columns.tolist())

['description', 'alertlevel', 'alertscore', 'episodealertlevel', 'episodealertscore', 'country', 'fromdate', 'todate', 'severity (magnitude)', 'source', 'iso3', 'Death', 'Displaced', 'gdacs_id', 'longitude', 'latitude', 'disaster_type']

In [13]:
drought["disaster_type"] = "Drought"
earthquake["disaster_type"] = "Earthquake"
eruption["disaster_type"] = "Eruption"
flood["disaster_type"] = "Flood"
forest_fires["disaster_type"] = "Forest Fire"
tropical_cyclone["disaster_type"] = "Tropical Cyclone"

In [14]:
master_columns = [
    "description",
    "alertlevel",
    "alertscore",
    "episodealertlevel",
    "episodealertscore",
    "country",
    "fromdate",
    "todate",
    "iso3",
    "gdacs_id",
    "longitude",
    "latitude",
    "disaster_type"
]

In [15]:
def prepare_for_merge(df):
    df = df.copy()

    for column in master_columns:
        if column not in df.columns:
            df[column] = np.nan

    return df[master_columns]

In [16]:
drought = prepare_for_merge(drought)
earthquake = prepare_for_merge(earthquake)
eruption = prepare_for_merge(eruption)
flood = prepare_for_merge(flood)
forest_fires = prepare_for_merge(forest_fires)
tropical_cyclone = prepare_for_merge(tropical_cyclone)

In [17]:
master_disaster_dataset = pd.concat(
    [
        drought,
        earthquake,
        eruption,
        flood,
        forest_fires,
        tropical_cyclone
    ],
    ignore_index=True
)

In [18]:
print("Shape:", master_disaster_dataset.shape)

display(master_disaster_dataset.head())

Shape: (26173, 13)

,description,alertlevel,alertscore,episodealertlevel,episodealertscore,country,fromdate,todate,iso3,gdacs_id,longitude,latitude,disaster_type
0,"Green Drought in Germany, Denmark, France, Lat...",Green,1.0,NaN,0.25,"Germany, Denmark, France, Latvia, Poland, Sweden",2017-07-21,2019-02-09 15:07:00,DEU,DR 1012168,11.087,53.882,Drought
1,Green Drought in Uzbekistan from: 21 Nov 2017 ...,Green,1.0,NaN,0.75,Uzbekistan,2017-11-21,2018-09-06 09:57:00,UZB,DR 1012172,65.500,40.996,Drought
2,Green Drought in Brazil from: 21 Dec 2017 to:...,Green,1.0,NaN,0.50,Brazil,2017-12-21,2018-09-06 09:57:00,BRA,DR 1012174,-50.105,-21.917,Drought
3,Orange Drought in Australia from: 21 Feb 2018 ...,Orange,2.0,NaN,1.00,Australia,2018-02-21,2018-11-24 16:27:00,AUS,DR 1012191,144.500,-33.500,Drought
4,Orange Drought in Madagascar from: 21 Mar 2018...,Orange,2.0,NaN,1.50,Madagascar,2018-03-21,2018-09-13 13:57:00,MDG,DR 1012304,46.464,-19.498,Drought

In [19]:
print(master_disaster_dataset["disaster_type"].value_counts())

disaster_type
Earthquake          20290
Forest Fire          3051
Flood                2126
Tropical Cyclone      405
Drought               240
Eruption               61
Name: count, dtype: int64

In [20]:
master_disaster_dataset.to_csv(
    "master_disaster_dataset.csv",
    index=False
)

print("master_disaster_dataset.csv created successfully!")

master_disaster_dataset.csv created successfully!

In [21]:
master_disaster_dataset

,description,alertlevel,alertscore,episodealertlevel,episodealertscore,country,fromdate,todate,iso3,gdacs_id,longitude,latitude,disaster_type
0,"Green Drought in Germany, Denmark, France, Lat...",Green,1.0,NaN,0.25,"Germany, Denmark, France, Latvia, Poland, Sweden",2017-07-21,2019-02-09 15:07:00,DEU,DR 1012168,11.087,53.882,Drought
1,Green Drought in Uzbekistan from: 21 Nov 2017 ...,Green,1.0,NaN,0.75,Uzbekistan,2017-11-21,2018-09-06 09:57:00,UZB,DR 1012172,65.500,40.996,Drought
2,Green Drought in Brazil from: 21 Dec 2017 to:...,Green,1.0,NaN,0.50,Brazil,2017-12-21,2018-09-06 09:57:00,BRA,DR 1012174,-50.105,-21.917,Drought
3,Orange Drought in Australia from: 21 Feb 2018 ...,Orange,2.0,NaN,1.00,Australia,2018-02-21,2018-11-24 16:27:00,AUS,DR 1012191,144.500,-33.500,Drought
4,Orange Drought in Madagascar from: 21 Mar 2018...,Orange,2.0,NaN,1.50,Madagascar,2018-03-21,2018-09-13 13:57:00,MDG,DR 1012304,46.464,-19.498,Drought
...,...,...,...,...,...,...,...,...,...,...,...,...,...
26168,Green Tropical Cyclone COURTNEY-25 off-shore f...,Green,1.0,Green,1.00,NaN,2025-03-24 12:00:00,2025-04-01 06:00:00,-1,231 km/h,88.400,-25.000,Tropical Cyclone
26169,Green Tropical Cyclone DIANNE-25 in Australia ...,Green,1.0,Green,1.00,NaN,2025-03-28 00:00:00,2025-03-28 18:00:00,AUS,83 km/h,123.800,-16.200,Tropical Cyclone
26170,Green Tropical Cyclone ALVIN-25 in Mexico from...,Green,1.0,Green,1.00,NaN,2025-05-28 21:00:00,2025-05-31 15:00:00,MEX,93 km/h,-109.500,20.700,Tropical Cyclone
26171,Green Tropical Cyclone FLOSSIE-25 in Mexico fr...,Green,1.0,Green,1.00,NaN,2025-06-29 09:00:00,2025-07-03 21:00:00,-1,185 km/h,-112.400,21.200,Tropical Cyclone
26172,Green Tropical Cyclone BARRY-25 in Mexico from...,Green,1.0,Green,1.00,NaN,2025-06-28 21:00:00,2025-06-30 09:00:00,MEX,74 km/h,-99.200,23.000,Tropical Cyclone

In [22]:
drought = standardize_columns(drought)
earthquake = standardize_columns(earthquake)
eruption = standardize_columns(eruption)
flood = standardize_columns(flood)
forest_fires = standardize_columns(forest_fires)
tropical_cyclone = standardize_columns(tropical_cyclone)

print("Column names standardized successfully.")

Column names standardized successfully.

In [23]:
if "Unnamed: 0" in flood.columns:
    flood = flood.drop(columns=["Unnamed: 0"])

print(flood.columns.tolist())

['description', 'alertlevel', 'alertscore', 'episodealertlevel', 'episodealertscore', 'country', 'fromdate', 'todate', 'iso3', 'gdacs_id', 'longitude', 'latitude', 'disaster_type']

In [24]:
drought["disaster_type"] = "Drought"
earthquake["disaster_type"] = "Earthquake"
eruption["disaster_type"] = "Eruption"
flood["disaster_type"] = "Flood"
forest_fires["disaster_type"] = "Forest Fire"
tropical_cyclone["disaster_type"] = "Tropical Cyclone"

print("Disaster type added successfully.")

Disaster type added successfully.

In [25]:
master_columns = [
    "description",
    "alertlevel",
    "alertscore",
    "episodealertlevel",
    "episodealertscore",
    "country",
    "fromdate",
    "todate",
    "iso3",
    "gdacs_id",
    "longitude",
    "latitude",
    "disaster_type"
]

print("Master columns defined successfully.")

Master columns defined successfully.

In [26]:
def prepare_for_merge(df):
    df = df.copy()

    for column in master_columns:
        if column not in df.columns:
            df[column] = np.nan

    return df[master_columns]

In [27]:
drought = prepare_for_merge(drought)
earthquake = prepare_for_merge(earthquake)
eruption = prepare_for_merge(eruption)
flood = prepare_for_merge(flood)
forest_fires = prepare_for_merge(forest_fires)
tropical_cyclone = prepare_for_merge(tropical_cyclone)

print("All 6 datasets are ready to be combined.")

All 6 datasets are ready to be combined.

In [28]:
master_disaster_dataset = pd.concat(
    [
        drought,
        earthquake,
        eruption,
        flood,
        forest_fires,
        tropical_cyclone
    ],
    ignore_index=True
)

print("All 6 datasets combined successfully.")

All 6 datasets combined successfully.

In [29]:
print("Shape:", master_disaster_dataset.shape)

display(master_disaster_dataset.head())

Shape: (26173, 13)

,description,alertlevel,alertscore,episodealertlevel,episodealertscore,country,fromdate,todate,iso3,gdacs_id,longitude,latitude,disaster_type
0,"Green Drought in Germany, Denmark, France, Lat...",Green,1.0,NaN,0.25,"Germany, Denmark, France, Latvia, Poland, Sweden",2017-07-21,2019-02-09 15:07:00,DEU,DR 1012168,11.087,53.882,Drought
1,Green Drought in Uzbekistan from: 21 Nov 2017 ...,Green,1.0,NaN,0.75,Uzbekistan,2017-11-21,2018-09-06 09:57:00,UZB,DR 1012172,65.500,40.996,Drought
2,Green Drought in Brazil from: 21 Dec 2017 to:...,Green,1.0,NaN,0.50,Brazil,2017-12-21,2018-09-06 09:57:00,BRA,DR 1012174,-50.105,-21.917,Drought
3,Orange Drought in Australia from: 21 Feb 2018 ...,Orange,2.0,NaN,1.00,Australia,2018-02-21,2018-11-24 16:27:00,AUS,DR 1012191,144.500,-33.500,Drought
4,Orange Drought in Madagascar from: 21 Mar 2018...,Orange,2.0,NaN,1.50,Madagascar,2018-03-21,2018-09-13 13:57:00,MDG,DR 1012304,46.464,-19.498,Drought

In [30]:
print(master_disaster_dataset["disaster_type"].value_counts())

disaster_type
Earthquake          20290
Forest Fire          3051
Flood                2126
Tropical Cyclone      405
Drought               240
Eruption               61
Name: count, dtype: int64

In [31]:
master_disaster_dataset.to_csv(
    "master_disaster_dataset.csv",
    index=False
)

print("master_disaster_dataset.csv created successfully!")

master_disaster_dataset.csv created successfully!

In [32]:
print("Columns:")
print(master_disaster_dataset.columns.tolist())

print("\nMissing values:")
print(master_disaster_dataset.isnull().sum())

Columns:
['description', 'alertlevel', 'alertscore', 'episodealertlevel', 'episodealertscore', 'country', 'fromdate', 'todate', 'iso3', 'gdacs_id', 'longitude', 'latitude', 'disaster_type']

Missing values:
description              0
alertlevel               0
alertscore               0
episodealertlevel     3291
episodealertscore        0
country               2211
fromdate                 0
todate                   0
iso3                  1081
gdacs_id             20290
longitude                0
latitude                 0
disaster_type            0
dtype: int64

In [33]:
print("Missing values by disaster type:")
print(
    master_disaster_dataset
    .groupby("disaster_type")
    .apply(lambda x: x.isnull().sum())
)

Missing values by disaster type:
                  description  alertlevel  alertscore  episodealertlevel  \
disaster_type
Drought                     0           0           0                240
Earthquake                  0           0           0                  0
Eruption                    0           0           0                  0
Flood                       0           0           0                  0
Forest Fire                 0           0           0               3051
Tropical Cyclone            0           0           0                  0

                  episodealertscore  country  fromdate  todate  iso3  \
disaster_type
Drought                           0        0         0       0     0
Earthquake                        0     1806         0       0  1081
Eruption                          0        0         0       0     0
Flood                             0        0         0       0     0
Forest Fire                       0        0         0       0     0
Tropical Cyclone                  0      405         0       0     0

                  gdacs_id  longitude  latitude
disaster_type
Drought                  0          0         0
Earthquake           20290          0         0
Eruption                 0          0         0
Flood                    0          0         0
Forest Fire              0          0         0
Tropical Cyclone         0          0         0

In [34]:
print("Duplicate rows:", master_disaster_dataset.duplicated().sum())

Duplicate rows: 0

In [35]:
print(master_disaster_dataset.dtypes)

description              str
alertlevel               str
alertscore           float64
episodealertlevel     object
episodealertscore    float64
country               object
fromdate                 str
todate                   str
iso3                     str
gdacs_id              object
longitude            float64
latitude             float64
disaster_type            str
dtype: object

In [36]:
master_disaster_dataset["fromdate"] = pd.to_datetime(
    master_disaster_dataset["fromdate"],
    errors="coerce"
)

master_disaster_dataset["todate"] = pd.to_datetime(
    master_disaster_dataset["todate"],
    errors="coerce"
)

print(master_disaster_dataset[["fromdate", "todate"]].dtypes)

fromdate    datetime64[us]
todate      datetime64[us]
dtype: object

In [37]:
print("Missing fromdate:", master_disaster_dataset["fromdate"].isnull().sum())
print("Missing todate:", master_disaster_dataset["todate"].isnull().sum())

Missing fromdate: 22882
Missing todate: 3051

In [38]:
master_disaster_dataset["fromdate"] = pd.to_datetime(
    master_disaster_dataset["fromdate"],
    format="mixed",
    errors="coerce"
)

master_disaster_dataset["todate"] = pd.to_datetime(
    master_disaster_dataset["todate"],
    format="mixed",
    errors="coerce"
)

print("Missing fromdate:", master_disaster_dataset["fromdate"].isnull().sum())
print("Missing todate:", master_disaster_dataset["todate"].isnull().sum())

Missing fromdate: 22882
Missing todate: 3051

In [39]:
print(master_disaster_dataset["fromdate"].head(20))
print("\n--- TODATE ---")
print(master_disaster_dataset["todate"].head(20))

0    2017-07-21
1    2017-11-21
2    2017-12-21
3    2018-02-21
4    2018-03-21
5    2018-04-21
6    2018-04-21
7    2018-04-21
8    2018-05-21
9    2018-05-21
10   2018-05-21
11   2018-05-11
12   2018-05-21
13   2018-06-21
14   2018-06-21
15   2018-06-21
16   2018-06-21
17   2018-07-21
18   2018-07-21
19   2018-07-21
Name: fromdate, dtype: datetime64[us]

--- TODATE ---
0    2019-02-09 15:07:00
1    2018-09-06 09:57:00
2    2018-09-06 09:57:00
3    2018-11-24 16:27:00
4    2018-09-13 13:57:00
5    2018-11-24 16:27:00
6    2018-10-10 08:17:00
7    2018-08-29 15:17:00
8    2018-12-30 14:05:00
9    2018-10-28 15:37:00
10   2018-10-10 08:17:00
11   2018-10-10 08:17:00
12   2018-08-20 10:37:15
13   2019-02-16 15:47:00
14   2018-11-16 15:57:00
15   2018-10-10 08:17:00
16   2018-10-10 08:17:00
17   2019-01-26 17:07:00
18   2018-12-30 14:05:00
19   2018-11-24 16:27:00
Name: todate, dtype: datetime64[us]

In [40]:
print("\nFromdate data types:")
print(master_disaster_dataset["fromdate"].map(type).value_counts())

print("\nTodate data types:")
print(master_disaster_dataset["todate"].map(type).value_counts())

Fromdate data types:
fromdate
<class 'pandas.api.typing.NaTType'>    22882
<class 'pandas.Timestamp'>              3291
Name: count, dtype: int64

Todate data types:
todate
<class 'pandas.Timestamp'>             23122
<class 'pandas.api.typing.NaTType'>     3051
Name: count, dtype: int64

In [41]:
print("Drought fromdate:")
print(drought["fromdate"].head())

print("\nEarthquake fromdate:")
print(earthquake["fromdate"].head())

print("\nEruption fromdate:")
print(eruption["fromdate"].head())

print("\nFlood fromdate:")
print(flood["fromdate"].head())

print("\nForest Fire fromdate:")
print(forest_fires["fromdate"].head())

print("\nTropical Cyclone fromdate:")
print(tropical_cyclone["fromdate"].head())

Drought fromdate:
0    2017-07-21
1    2017-11-21
2    2017-12-21
3    2018-02-21
4    2018-03-21
Name: fromdate, dtype: str

Earthquake fromdate:
0    2000-01-19 00:00:00
1    2000-02-14 00:00:00
2    2000-02-03 00:00:00
3    2000-04-05 04:37:00
4    2000-05-04 04:21:00
Name: fromdate, dtype: str

Eruption fromdate:
0    2011-09-20 18:00:00
1    2011-10-28 09:48:00
2    2011-12-30 18:00:00
3    2012-01-30 07:31:00
4    2012-02-28 04:30:00
Name: fromdate, dtype: str

Flood fromdate:
0    2000-01-26 00:00:00
1    2000-01-28 00:00:00
2    2000-01-08 00:00:00
3    2000-01-01 00:00:00
4    2000-02-17 00:00:00
Name: fromdate, dtype: str

Forest Fire fromdate:
0    2021-02-23
1    2021-02-25
2    2021-02-25
3    2021-02-23
4    2021-02-23
Name: fromdate, dtype: str

Tropical Cyclone fromdate:
0    2008-04-28 06:00:00
1    2011-05-22 00:00:00
2    2011-07-28 06:00:00
3    2011-07-31 15:00:00
4    2011-07-26 00:00:00
Name: fromdate, dtype: str

In [42]:
drought = prepare_for_merge(drought)
earthquake = prepare_for_merge(earthquake)
eruption = prepare_for_merge(eruption)
flood = prepare_for_merge(flood)
forest_fires = prepare_for_merge(forest_fires)
tropical_cyclone = prepare_for_merge(tropical_cyclone)

In [43]:
master_disaster_dataset = pd.concat(
    [
        drought,
        earthquake,
        eruption,
        flood,
        forest_fires,
        tropical_cyclone
    ],
    ignore_index=True
)

In [44]:
master_disaster_dataset["fromdate"] = pd.to_datetime(
    master_disaster_dataset["fromdate"],
    format="mixed",
    errors="coerce"
)

master_disaster_dataset["todate"] = pd.to_datetime(
    master_disaster_dataset["todate"],
    format="mixed",
    errors="coerce"
)

In [45]:
print("Missing fromdate:", master_disaster_dataset["fromdate"].isnull().sum())
print("Missing todate:", master_disaster_dataset["todate"].isnull().sum())

Missing fromdate: 0
Missing todate: 0

In [46]:
print(master_disaster_dataset[["fromdate", "todate"]].dtypes)

fromdate    datetime64[us]
todate      datetime64[us]
dtype: object

In [47]:
master_disaster_dataset["year"] = master_disaster_dataset["fromdate"].dt.year

master_disaster_dataset["month"] = master_disaster_dataset["fromdate"].dt.month

master_disaster_dataset["duration_days"] = (
    master_disaster_dataset["todate"] -
    master_disaster_dataset["fromdate"]
).dt.total_seconds() / (24 * 60 * 60)

master_disaster_dataset["duration_days"] = master_disaster_dataset["duration_days"].round(2)

print("Date features created successfully.")

Date features created successfully.

In [48]:
display(
    master_disaster_dataset[
        ["fromdate", "todate", "year", "month", "duration_days"]
    ].head()
)

    fromdate              todate  year  month  duration_days
0 2017-07-21 2019-02-09 15:07:00  2017      7         568.63
1 2017-11-21 2018-09-06 09:57:00  2017     11         289.41
2 2017-12-21 2018-09-06 09:57:00  2017     12         259.41
3 2018-02-21 2018-11-24 16:27:00  2018      2         276.69
4 2018-03-21 2018-09-13 13:57:00  2018      3         176.58

In [49]:
master_disaster_dataset[
    [
        "alertscore",
        "episodealertscore",
        "longitude",
        "latitude",
        "year",
        "month",
        "duration_days"
    ]
].describe()

,alertscore,episodealertscore,longitude,latitude,year,month,duration_days
count,26173.000000,26173.000000,26173.000000,26173.000000,26173.000000,26173.000000,26173.000000
mean,1.031406,0.375748,31.276689,10.646761,2012.891300,6.498873,4.689610
std,0.202214,0.444964,109.969085,28.816074,6.652943,3.453348,28.490087
min,1.000000,-1.000000,-179.990000,-66.860000,2000.000000,1.000000,-1.000000
25%,1.000000,0.000000,-70.590000,-11.202900,2007.000000,3.000000,0.000000
50%,1.000000,0.500000,52.588300,9.738000,2013.000000,6.000000,0.000000
75%,1.000000,0.500000,128.460200,36.284800,2018.000000,10.000000,0.000000
max,3.000000,3.786233,180.000000,86.893200,2025.000000,12.000000,1056.000000

In [50]:
print("Negative duration:", (master_disaster_dataset["duration_days"] < 0).sum())
print("Zero duration:", (master_disaster_dataset["duration_days"] == 0).sum())
print("Duration > 365 days:", (master_disaster_dataset["duration_days"] > 365).sum())

Negative duration: 1
Zero duration: 20650
Duration > 365 days: 43

In [51]:
print("Negative duration record:")
print(
    master_disaster_dataset[
        master_disaster_dataset["duration_days"] < 0
    ][
        ["description", "disaster_type", "fromdate", "todate", "duration_days"]
    ]
)

print("\nDuration > 365 days:")
print(
    master_disaster_dataset[
        master_disaster_dataset["duration_days"] > 365
    ][
        ["description", "disaster_type", "fromdate", "todate", "duration_days"]
    ].head(20)
)

Negative duration record:
                                             description disaster_type  \
21658  GREEN Flood in Indonesia from: 24 Apr 2008 00 ...         Flood

        fromdate     todate  duration_days
21658 2008-04-24 2008-04-23           -1.0

Duration > 365 days:
                                           description disaster_type  \
0    Green Drought in Germany, Denmark, France, Lat...       Drought
33   Orange Drought in Belize, Guatemala, Honduras,...       Drought
38   Red Drought in Angola, Botswana, Mozambique, N...       Drought
39   Green Drought in Philippines from: 21 Oct 2018...       Drought
43   Green Drought in Cambodia, Laos, Myanmar, Thai...       Drought
49   Orange Drought in Bolivia, Brazil from: 21 Dec...       Drought
84   Orange Drought in Argentina from: 21 Jun 2019 ...       Drought
97   Green Drought in Canada, United States from: 2...       Drought
103  Green Drought in Mozambique from: 21 Mar 2020 ...       Drought
117  Green Drought in Brazil from: 21 Jul 2020  to:...       Drought
120  Green Drought in Armenia, Azerbaijan, Iran fro...       Drought
122  Green Drought in Cameroon, Nigeria from: 21 Se...       Drought
123  Green Drought in Angola from: 21 Sep 2020  to:...       Drought
125  Green Drought in Argentina, Chile from: 21 Oct...       Drought
126  Green Drought in Afghanistan, Kazakhstan, Taji...       Drought
127  Green Drought in Argentina, Chile from: 21 Oct...       Drought
128  Green Drought in Italy from: 21 Nov 2020  to: ...       Drought
140  Green Drought in Islamic Republic of Iran, Kyr...       Drought
146  Green Drought in Brazil from: 21 Jan 2022  to:...       Drought
147  Green Drought in Greece, Türkiye from: 21 Jan ...       Drought

      fromdate              todate  duration_days
0   2017-07-21 2019-02-09 15:07:00         568.63
33  2018-09-21 2020-03-03 14:37:00         529.61
38  2018-10-21 2020-03-24 16:37:00         520.69
39  2018-10-21 2020-01-06 14:47:00         442.62
43  2018-11-21 2020-10-20 00:00:00         699.00
49  2018-12-21 2020-08-10 15:27:00         598.64
84  2019-06-21 2020-12-30 00:00:00         558.00
97  2020-02-21 2022-02-09 00:00:00         719.00
103 2020-03-21 2021-04-30 00:00:00         405.00
117 2020-07-21 2021-10-17 00:00:00         453.00
120 2020-08-21 2021-11-07 00:00:00         443.00
122 2020-09-21 2021-12-13 00:00:00         448.00
123 2020-09-21 2021-12-05 00:00:00         440.00
125 2020-10-21 2023-06-19 00:00:00         971.00
126 2020-10-21 2022-09-28 00:00:00         707.00
127 2020-10-21 2022-05-30 00:00:00         586.00
128 2020-11-21 2021-12-13 00:00:00         387.00
140 2021-10-21 2024-07-03 00:00:00         986.00
146 2022-01-21 2023-07-12 00:00:00         537.00
147 2022-01-21 2023-06-19 00:00:00         514.00

In [52]:
master_disaster_dataset.loc[
    master_disaster_dataset["duration_days"] < 0,
    "duration_days"
] = 0

print("Negative duration after cleaning:",
      (master_disaster_dataset["duration_days"] < 0).sum())

Negative duration after cleaning: 0