In [391]:
import pandas as pd
import numpy as np

drought = pd.read_csv("Drought_clean.csv")
earthquake = pd.read_csv("Earthquake_clean.csv")
eruption = pd.read_csv("Eruption_clean.csv")
flood = pd.read_csv("Flood_clean.csv")
forest_fires = pd.read_csv("Forest_Fires_clean.csv")
tropical_cyclone = pd.read_csv("Tropical_Cyclone_clean.csv")

In [392]:
print(drought.shape)
print(earthquake.shape)
print(eruption.shape)
print(flood.shape)
print(forest_fires.shape)
print(tropical_cyclone.shape)

(240, 14)
(20290, 16)
(61, 18)
(2126, 17)
(3051, 14)
(405, 20)

In [393]:
print(drought.columns)
print(earthquake.columns)
print(eruption.columns)
print(flood.columns)
print(forest_fires.columns)
print(tropical_cyclone.columns)

Index(['Description', 'Alertlevel', 'Alertscore', 'Episodealertscore',
       'Country', 'Fromdate', 'Todate', 'Severity (km2)', 'Iso3', 'Gdacs id',
       'Duration (days)', 'Impact', 'Longitude', 'Latitude'],
      dtype='str')
Index(['description', 'alertlevel', 'alertscore', 'episodealertlevel',
       'episodealertscore', 'country', 'fromdate', 'todate', 'source', 'iso3',
       'Earthquake Magnitude (M)', 'Capacity', 'Depth (km)', 'longitude',
       'latitude', 'Exposed Population (within 100 km)'],
      dtype='str')
Index(['description', 'alertlevel', 'alertscore', 'episodealertlevel',
       'episodealertscore', 'country', 'fromdate', 'todate', 'severity',
       'source', 'iso3', 'GDACS ID', 'Exposed Population 30km',
       'Exposed Population 100km', 'Max Volc. Explosivity Index VEI',
       'Population Exposure Index PEI', 'longitude', 'latitude'],
      dtype='str')
Index(['Unnamed: 0', 'description', 'alertlevel', 'alertscore',
       'episodealertlevel', 'episodealertscore', 'country', 'fromdate',
       'todate', 'severity (magnitude)', 'source', 'iso3', 'Death',
       'Displaced', 'GDACS_ID', 'longitude', 'latitude'],
      dtype='str')
Index(['description', 'alertlevel', 'alertscore', 'episodealertscore',
       'country', 'fromdate', 'todate', 'severity (ha)', 'iso3', 'GDACS ID',
       'People affected', 'Duration (days)', 'longitude', 'latitude'],
      dtype='str')
Index(['description', 'alertlevel', 'alertscore', 'episodealertlevel',
       'episodealertscore', 'fromdate', 'todate', 'severity', 'severitytext',
       'source', 'iso3', 'GDACS ID', 'Exposed countries', 'Exposed population',
       'Maximum wind speed (km/h)', 'Maximum storm surge (m)', 'Vulnerability',
       'longitude', 'latitude', 'Category'],
      dtype='str')

In [394]:
print("Drought:")
display(drought.head())

print("Earthquake:")
display(earthquake.head())

print("Eruption:")
display(eruption.head())

print("Flood:")
display(flood.head())

print("Forest Fires:")
display(forest_fires.head())

print("Tropical Cyclone:")
display(tropical_cyclone.head())

Drought:

,Description,Alertlevel,Alertscore,Episodealertscore,Country,Fromdate,Todate,Severity (km2),Iso3,Gdacs id,Duration (days),Impact,Longitude,Latitude
0,"Green Drought in Germany, Denmark, France, Lat...",Green,1.0,0.25,"Germany, Denmark, France, Latvia, Poland, Sweden",2017-07-21,2019-02-09 15:07:00,80936.0,DEU,DR 1012168,569.0,Minor impact for agricultural drought in 80936...,11.087,53.882
1,Green Drought in Uzbekistan from: 21 Nov 2017 ...,Green,1.0,0.75,Uzbekistan,2017-11-21,2018-09-06 09:57:00,18686.0,UZB,DR 1012172,289.0,Minor impact for agricultural drought in 18686...,65.500,40.996
2,Green Drought in Brazil from: 21 Dec 2017 to:...,Green,1.0,0.50,Brazil,2017-12-21,2018-09-06 09:57:00,87604.0,BRA,DR 1012174,259.0,Minor impact for agricultural drought in 87604...,-50.105,-21.917
3,Orange Drought in Australia from: 21 Feb 2018 ...,Orange,2.0,1.00,Australia,2018-02-21,2018-11-24 16:27:00,142608.0,AUS,DR 1012191,277.0,Medium impact for agricultural drought in 1426...,144.500,-33.500
4,Orange Drought in Madagascar from: 21 Mar 2018...,Orange,2.0,1.50,Madagascar,2018-03-21,2018-09-13 13:57:00,68692.0,MDG,DR 1012304,177.0,Medium impact for agricultural drought in 6869...,46.464,-19.498

Earthquake:

,description,alertlevel,alertscore,episodealertlevel,episodealertscore,country,fromdate,todate,source,iso3,Earthquake Magnitude (M),Capacity,Depth (km),longitude,latitude,Exposed Population (within 100 km)
0,Red M 6.4 Earthquake in Afghanistan at: 19 Jan...,Red,3.0,Red,3.0,Afghanistan,2000-01-19 00:00:00,2000-01-19 00:00:00,NEIC,AFG,6.4,-1,0.0,70.400,36.200,460000.0
1,Green M 4.9 Earthquake in Iran at: 14 Feb 2000...,Green,1.0,Green,0.5,Iran,2000-02-14 00:00:00,2000-02-14 00:00:00,NEIC,IRN,4.9,-1,0.0,58.175,35.217,440000.0
2,Green M 5.3 Earthquake in Iran at: 03 Feb 2000...,Green,1.0,Green,0.5,Iran,2000-02-03 00:00:00,2000-02-03 00:00:00,NEIC,IRN,5.3,-1,0.0,58.218,35.288,470000.0
3,"Green M 5.5 Earthquake in Crete, Greece at: 05...",Green,1.0,Green,0.0,"Crete, Greece",2000-04-05 04:37:00,2000-04-05 04:37:00,NGDC,NaN,5.5,1.1 (),10.0,25.690,34.220,30000.0
4,Orange M 7.6 Earthquake in Indonesia at: 04 Ma...,Orange,2.0,Orange,1.5,Indonesia,2000-05-04 04:21:00,2000-05-04 04:21:00,NGDC,IDN,7.6,4.8 (Indonesia),10.0,123.573,-1.105,90000.0

Eruption:

,description,alertlevel,alertscore,episodealertlevel,episodealertscore,country,fromdate,todate,severity,source,iso3,GDACS ID,Exposed Population 30km,Exposed Population 100km,Max Volc. Explosivity Index VEI,Population Exposure Index PEI,longitude,latitude
0,Green Eruption Iskut-Unuk River Cones in Canad...,Green,1.0,Green,0.0,Canada,2011-09-20 18:00:00,2011-09-20 18:00:00,0.0,MONTREAL,-1,VO 360,-1.0,0.0,-1.0,-1.0,-130.550000,56.583333
1,"Green Eruption Hudson, Cerro in Chile-S at: 28...",Green,1.0,Green,0.0,Chile-S,2011-10-28 09:48:00,2011-10-28 09:48:00,0.0,BUENOS AIRES,-1,VO 484,-1.0,0.0,-1.0,-1.0,-72.966666,-45.900000
2,Green Eruption Yasur in Vanuatu-SW Pacific at:...,Green,1.0,Green,0.0,Vanuatu-SW Pacific,2011-12-30 18:00:00,2011-12-30 18:00:00,0.0,WELLINGTON,-1,VO 103,-1.0,0.0,-1.0,-1.0,169.441666,-19.533333
3,Green Eruption Pagan in Mariana Is-C Pacific a...,Green,1.0,Green,0.0,Mariana Is-C Pacific,2012-01-30 07:31:00,2012-01-30 07:31:00,0.0,WASHINGTON,-1,VO 253,-1.0,0.0,-1.0,-1.0,145.800000,18.133333
4,Orange Eruption Dukono in Halmahera-Indonesia ...,Orange,2.0,Orange,2.0,Halmahera-Indonesia,2012-02-28 04:30:00,2012-02-28 04:30:00,0.0,DARWIN,-1,VO 178,-1.0,0.0,-1.0,-1.0,127.883333,1.683333

Flood:

,Unnamed: 0,description,alertlevel,alertscore,episodealertlevel,episodealertscore,country,fromdate,todate,severity (magnitude),source,iso3,Death,Displaced,GDACS_ID,longitude,latitude
0,0,ORANGE Flood in Mozambique from: 26 Jan 2000 0...,ORANGE,2.0,ORANGE,2.0,Mozambique,2000-01-26 00:00:00,2000-03-27 23:59:59,7.74,DFO,MOZ,929.0,733000.0,FL 1583,31.712,-27.822
1,1,GREEN Flood in Philippines from: 28 Jan 2000 0...,GREEN,1.0,GREEN,1.0,Philippines,2000-01-28 00:00:00,2000-02-01 23:59:59,4.92,DFO,PHL,23.0,20000.0,FL 1584,126.100,7.199
2,2,GREEN Flood in Angola from: 08 Jan 2000 00 to:...,GREEN,1.0,GREEN,1.0,Angola,2000-01-08 00:00:00,2000-01-15 23:59:59,5.58,DFO,AGO,31.0,70000.0,FL 1582,13.246,-14.145
3,3,ORANGE Flood in Southeastern Brazil from: 01 J...,ORANGE,2.0,Orange,2.0,Southeastern Brazil,2000-01-01 00:00:00,2000-01-01 00:00:00,6.55,DFO,,40.0,100000.0,FL 1581,-49.304,-24.891
4,4,RED Flood in Madagascar from: 17 Feb 2000 00 t...,RED,3.0,RED,3.0,Madagascar,2000-02-17 00:00:00,2000-03-11 23:59:59,6.79,DFO,MDG,200.0,800000.0,FL 1587,47.296,-15.783

Forest Fires:

,description,alertlevel,alertscore,episodealertscore,country,fromdate,todate,severity (ha),iso3,GDACS ID,People affected,Duration (days),longitude,latitude
0,Green Forest fires in Laos from: 23 Feb 2021 t...,Green,1.0,1.0,Laos,2021-02-23,2021-03-23,5070.0,LAO,WF 1000144,0.0,28.0,105.659937,17.335162
1,Green Forest fires in India from: 25 Feb 2021 ...,Green,1.0,1.0,India,2021-02-25,2021-03-11,9866.0,IND,WF 1000128,35445.0,14.0,85.875408,22.856787
2,Green Forest fires in Argentina from: 25 Feb 2...,Green,1.0,1.0,Argentina,2021-02-25,2021-03-08,5326.0,ARG,WF 1000127,0.0,11.0,-71.362698,-43.813590
3,Green Forest fires in Myanmar from: 23 Feb 202...,Green,1.0,1.0,Myanmar,2021-02-23,2021-03-08,5353.0,MMR,WF 1000143,0.0,13.0,97.226779,22.268084
4,Green Forest fires in India from: 23 Feb 2021 ...,Green,1.0,1.0,India,2021-02-23,2021-03-07,7572.0,IND,WF 1000142,8550.0,12.0,82.750550,20.166615

Tropical Cyclone:

,description,alertlevel,alertscore,episodealertlevel,episodealertscore,fromdate,todate,severity,severitytext,source,iso3,GDACS ID,Exposed countries,Exposed population,Maximum wind speed (km/h),Maximum storm surge (m),Vulnerability,longitude,latitude,Category
0,Red Tropical Cyclone NARGIS-08 off-shore from:...,Red,3.0,Green,1.0,2008-04-28 06:00:00,2008-05-03 12:00:00,74.029824,Tropical Storm (maximum wind speed of 212 km/h),JTWC,,TC 10238,Off-shore,7000000.0,74.0,-1.0,-1,97.5,18.299999,-1.0
1,Orange Tropical Cyclone SONGDA-11 in Japan fro...,Orange,2.0,Green,1.0,2011-05-22 00:00:00,2011-05-29 12:00:00,64.373760,Tropical Depression (maximum wind speed of 259...,JRC,,TC 24054,Japan,0.0,64.0,-1.0,Low,136.6,34.400000,-1.0
2,Green Tropical Cyclone MUIFA-11 in Japan from:...,Green,1.0,Green,1.0,2011-07-28 06:00:00,2011-08-08 12:00:00,286.463232,Tropical Storm (maximum wind speed of 259 km/h),JRC,,TC 25110,Japan,1200000.0,286.0,-1.0,Low,124.9,40.300000,5.0
3,Green Tropical Cyclone EUGENE-11 off-shore fro...,Green,1.0,Green,1.0,2011-07-31 15:00:00,2011-08-06 09:00:00,222.089472,Tropical Storm (maximum wind speed of 222 km/h),JRC,,TC 25192,Off-shore,0.0,222.0,-1.0,-1,-127.1,18.900000,4.0
4,Green Tropical Cyclone NOCK-TEN-11 in Philippi...,Green,1.0,Green,1.0,2011-07-26 00:00:00,2011-07-30 12:00:00,120.700800,Tropical Storm (maximum wind speed of 120 km/h),JRC,,TC 25101,"Philippines,China,Vietnam",0.0,121.0,-1.0,High,105.5,19.100000,1.0

In [395]:
print("Drought:", drought.columns.tolist())
print("Earthquake:", earthquake.columns.tolist())
print("Eruption:", eruption.columns.tolist())
print("Flood:", flood.columns.tolist())
print("Forest Fires:", forest_fires.columns.tolist())
print("Tropical Cyclone:", tropical_cyclone.columns.tolist())

Drought: ['Description', 'Alertlevel', 'Alertscore', 'Episodealertscore', 'Country', 'Fromdate', 'Todate', 'Severity (km2)', 'Iso3', 'Gdacs id', 'Duration (days)', 'Impact', 'Longitude', 'Latitude']
Earthquake: ['description', 'alertlevel', 'alertscore', 'episodealertlevel', 'episodealertscore', 'country', 'fromdate', 'todate', 'source', 'iso3', 'Earthquake Magnitude (M)', 'Capacity', 'Depth (km)', 'longitude', 'latitude', 'Exposed Population (within 100 km)']
Eruption: ['description', 'alertlevel', 'alertscore', 'episodealertlevel', 'episodealertscore', 'country', 'fromdate', 'todate', 'severity', 'source', 'iso3', 'GDACS ID', 'Exposed Population 30km', 'Exposed Population 100km', 'Max Volc. Explosivity Index VEI', 'Population Exposure Index PEI', 'longitude', 'latitude']
Flood: ['Unnamed: 0', 'description', 'alertlevel', 'alertscore', 'episodealertlevel', 'episodealertscore', 'country', 'fromdate', 'todate', 'severity (magnitude)', 'source', 'iso3', 'Death', 'Displaced', 'GDACS_ID', 'longitude', 'latitude']
Forest Fires: ['description', 'alertlevel', 'alertscore', 'episodealertscore', 'country', 'fromdate', 'todate', 'severity (ha)', 'iso3', 'GDACS ID', 'People affected', 'Duration (days)', 'longitude', 'latitude']
Tropical Cyclone: ['description', 'alertlevel', 'alertscore', 'episodealertlevel', 'episodealertscore', 'fromdate', 'todate', 'severity', 'severitytext', 'source', 'iso3', 'GDACS ID', 'Exposed countries', 'Exposed population', 'Maximum wind speed (km/h)', 'Maximum storm surge (m)', 'Vulnerability', 'longitude', 'latitude', 'Category']

In [396]:
print("Drought:", drought.shape)
print("Earthquake:", earthquake.shape)
print("Eruption:", eruption.shape)
print("Flood:", flood.shape)
print("Forest Fires:", forest_fires.shape)
print("Tropical Cyclone:", tropical_cyclone.shape)

Drought: (240, 14)
Earthquake: (20290, 16)
Eruption: (61, 18)
Flood: (2126, 17)
Forest Fires: (3051, 14)
Tropical Cyclone: (405, 20)

In [397]:
print("Drought:", drought.columns.tolist())
print("Earthquake:", earthquake.columns.tolist())
print("Eruption:", eruption.columns.tolist())
print("Flood:", flood.columns.tolist())
print("Forest Fires:", forest_fires.columns.tolist())
print("Tropical Cyclone:", tropical_cyclone.columns.tolist())

Drought: ['Description', 'Alertlevel', 'Alertscore', 'Episodealertscore', 'Country', 'Fromdate', 'Todate', 'Severity (km2)', 'Iso3', 'Gdacs id', 'Duration (days)', 'Impact', 'Longitude', 'Latitude']
Earthquake: ['description', 'alertlevel', 'alertscore', 'episodealertlevel', 'episodealertscore', 'country', 'fromdate', 'todate', 'source', 'iso3', 'Earthquake Magnitude (M)', 'Capacity', 'Depth (km)', 'longitude', 'latitude', 'Exposed Population (within 100 km)']
Eruption: ['description', 'alertlevel', 'alertscore', 'episodealertlevel', 'episodealertscore', 'country', 'fromdate', 'todate', 'severity', 'source', 'iso3', 'GDACS ID', 'Exposed Population 30km', 'Exposed Population 100km', 'Max Volc. Explosivity Index VEI', 'Population Exposure Index PEI', 'longitude', 'latitude']
Flood: ['Unnamed: 0', 'description', 'alertlevel', 'alertscore', 'episodealertlevel', 'episodealertscore', 'country', 'fromdate', 'todate', 'severity (magnitude)', 'source', 'iso3', 'Death', 'Displaced', 'GDACS_ID', 'longitude', 'latitude']
Forest Fires: ['description', 'alertlevel', 'alertscore', 'episodealertscore', 'country', 'fromdate', 'todate', 'severity (ha)', 'iso3', 'GDACS ID', 'People affected', 'Duration (days)', 'longitude', 'latitude']
Tropical Cyclone: ['description', 'alertlevel', 'alertscore', 'episodealertlevel', 'episodealertscore', 'fromdate', 'todate', 'severity', 'severitytext', 'source', 'iso3', 'GDACS ID', 'Exposed countries', 'Exposed population', 'Maximum wind speed (km/h)', 'Maximum storm surge (m)', 'Vulnerability', 'longitude', 'latitude', 'Category']

In [398]:
for name, df in {
    "Drought": drought,
    "Earthquake": earthquake,
    "Eruption": eruption,
    "Flood": flood,
    "Forest Fires": forest_fires,
    "Tropical Cyclone": tropical_cyclone
}.items():
    print(f"\n{name}")
    for col in df.columns:
        print(" -", col)

Drought
 - Description
 - Alertlevel
 - Alertscore
 - Episodealertscore
 - Country
 - Fromdate
 - Todate
 - Severity (km2)
 - Iso3
 - Gdacs id
 - Duration (days)
 - Impact
 - Longitude
 - Latitude

Earthquake
 - description
 - alertlevel
 - alertscore
 - episodealertlevel
 - episodealertscore
 - country
 - fromdate
 - todate
 - source
 - iso3
 - Earthquake Magnitude (M)
 - Capacity
 - Depth (km)
 - longitude
 - latitude
 - Exposed Population (within 100 km)

Eruption
 - description
 - alertlevel
 - alertscore
 - episodealertlevel
 - episodealertscore
 - country
 - fromdate
 - todate
 - severity
 - source
 - iso3
 - GDACS ID
 - Exposed Population 30km
 - Exposed Population 100km
 - Max Volc. Explosivity Index VEI
 - Population Exposure Index PEI
 - longitude
 - latitude

Flood
 - Unnamed: 0
 - description
 - alertlevel
 - alertscore
 - episodealertlevel
 - episodealertscore
 - country
 - fromdate
 - todate
 - severity (magnitude)
 - source
 - iso3
 - Death
 - Displaced
 - GDACS_ID
 - longitude
 - latitude

Forest Fires
 - description
 - alertlevel
 - alertscore
 - episodealertscore
 - country
 - fromdate
 - todate
 - severity (ha)
 - iso3
 - GDACS ID
 - People affected
 - Duration (days)
 - longitude
 - latitude

Tropical Cyclone
 - description
 - alertlevel
 - alertscore
 - episodealertlevel
 - episodealertscore
 - fromdate
 - todate
 - severity
 - severitytext
 - source
 - iso3
 - GDACS ID
 - Exposed countries
 - Exposed population
 - Maximum wind speed (km/h)
 - Maximum storm surge (m)
 - Vulnerability
 - longitude
 - latitude
 - Category

In [399]:
drought["disaster_type"] = "Drought"
earthquake["disaster_type"] = "Earthquake"
eruption["disaster_type"] = "Eruption"
flood["disaster_type"] = "Flood"
forest_fires["disaster_type"] = "Forest Fire"
tropical_cyclone["disaster_type"] = "Tropical Cyclone"

In [400]:
def standardize_columns(df):
    df = df.copy()
    df.columns = df.columns.str.strip()

    rename_map = {
        "Description": "description",
        "Alertlevel": "alertlevel",
        "Alertscore": "alertscore",
        "Episodealertlevel": "episodealertlevel",
        "Episodealertscore": "episodealertscore",
        "Country": "country",
        "Fromdate": "fromdate",
        "Todate": "todate",
        "Iso3": "iso3",
        "Gdacs id": "gdacs_id",
        "GDACS ID": "gdacs_id",
        "GDACS_ID": "gdacs_id",
        "Longitude": "longitude",
        "Latitude": "latitude"
    }

    df = df.rename(columns=rename_map)

    return df

In [401]:
drought = standardize_columns(drought)
earthquake = standardize_columns(earthquake)
eruption = standardize_columns(eruption)
flood = standardize_columns(flood)
forest_fires = standardize_columns(forest_fires)
tropical_cyclone = standardize_columns(tropical_cyclone)

In [402]:
if "Unnamed: 0" in flood.columns:
    flood = flood.drop(columns=["Unnamed: 0"])

print(flood.columns.tolist())

['description', 'alertlevel', 'alertscore', 'episodealertlevel', 'episodealertscore', 'country', 'fromdate', 'todate', 'severity (magnitude)', 'source', 'iso3', 'Death', 'Displaced', 'gdacs_id', 'longitude', 'latitude', 'disaster_type']

In [403]:
drought["disaster_type"] = "Drought"
earthquake["disaster_type"] = "Earthquake"
eruption["disaster_type"] = "Eruption"
flood["disaster_type"] = "Flood"
forest_fires["disaster_type"] = "Forest Fire"
tropical_cyclone["disaster_type"] = "Tropical Cyclone"

In [404]:
master_columns = [
    "description",
    "alertlevel",
    "alertscore",
    "episodealertlevel",
    "episodealertscore",
    "country",
    "fromdate",
    "todate",
    "iso3",
    "gdacs_id",
    "longitude",
    "latitude",
    "disaster_type"
]

In [405]:
def prepare_for_merge(df):
    df = df.copy()

    for column in master_columns:
        if column not in df.columns:
            df[column] = np.nan

    return df[master_columns]

In [406]:
drought = prepare_for_merge(drought)
earthquake = prepare_for_merge(earthquake)
eruption = prepare_for_merge(eruption)
flood = prepare_for_merge(flood)
forest_fires = prepare_for_merge(forest_fires)
tropical_cyclone = prepare_for_merge(tropical_cyclone)

In [407]:
master_disaster_dataset = pd.concat(
    [
        drought,
        earthquake,
        eruption,
        flood,
        forest_fires,
        tropical_cyclone
    ],
    ignore_index=True
)

In [408]:
print("Shape:", master_disaster_dataset.shape)

display(master_disaster_dataset.head())

Shape: (26173, 13)

,description,alertlevel,alertscore,episodealertlevel,episodealertscore,country,fromdate,todate,iso3,gdacs_id,longitude,latitude,disaster_type
0,"Green Drought in Germany, Denmark, France, Lat...",Green,1.0,NaN,0.25,"Germany, Denmark, France, Latvia, Poland, Sweden",2017-07-21,2019-02-09 15:07:00,DEU,DR 1012168,11.087,53.882,Drought
1,Green Drought in Uzbekistan from: 21 Nov 2017 ...,Green,1.0,NaN,0.75,Uzbekistan,2017-11-21,2018-09-06 09:57:00,UZB,DR 1012172,65.500,40.996,Drought
2,Green Drought in Brazil from: 21 Dec 2017 to:...,Green,1.0,NaN,0.50,Brazil,2017-12-21,2018-09-06 09:57:00,BRA,DR 1012174,-50.105,-21.917,Drought
3,Orange Drought in Australia from: 21 Feb 2018 ...,Orange,2.0,NaN,1.00,Australia,2018-02-21,2018-11-24 16:27:00,AUS,DR 1012191,144.500,-33.500,Drought
4,Orange Drought in Madagascar from: 21 Mar 2018...,Orange,2.0,NaN,1.50,Madagascar,2018-03-21,2018-09-13 13:57:00,MDG,DR 1012304,46.464,-19.498,Drought

In [409]:
print(master_disaster_dataset["disaster_type"].value_counts())

disaster_type
Earthquake          20290
Forest Fire          3051
Flood                2126
Tropical Cyclone      405
Drought               240
Eruption               61
Name: count, dtype: int64

In [410]:
master_disaster_dataset.to_csv(
    "master_disaster_dataset.csv",
    index=False
)

print("master_disaster_dataset.csv created successfully!")

master_disaster_dataset.csv created successfully!

In [411]:
master_disaster_dataset

,description,alertlevel,alertscore,episodealertlevel,episodealertscore,country,fromdate,todate,iso3,gdacs_id,longitude,latitude,disaster_type
0,"Green Drought in Germany, Denmark, France, Lat...",Green,1.0,NaN,0.25,"Germany, Denmark, France, Latvia, Poland, Sweden",2017-07-21,2019-02-09 15:07:00,DEU,DR 1012168,11.087,53.882,Drought
1,Green Drought in Uzbekistan from: 21 Nov 2017 ...,Green,1.0,NaN,0.75,Uzbekistan,2017-11-21,2018-09-06 09:57:00,UZB,DR 1012172,65.500,40.996,Drought
2,Green Drought in Brazil from: 21 Dec 2017 to:...,Green,1.0,NaN,0.50,Brazil,2017-12-21,2018-09-06 09:57:00,BRA,DR 1012174,-50.105,-21.917,Drought
3,Orange Drought in Australia from: 21 Feb 2018 ...,Orange,2.0,NaN,1.00,Australia,2018-02-21,2018-11-24 16:27:00,AUS,DR 1012191,144.500,-33.500,Drought
4,Orange Drought in Madagascar from: 21 Mar 2018...,Orange,2.0,NaN,1.50,Madagascar,2018-03-21,2018-09-13 13:57:00,MDG,DR 1012304,46.464,-19.498,Drought
...,...,...,...,...,...,...,...,...,...,...,...,...,...
26168,Green Tropical Cyclone COURTNEY-25 off-shore f...,Green,1.0,Green,1.00,NaN,2025-03-24 12:00:00,2025-04-01 06:00:00,-1,231 km/h,88.400,-25.000,Tropical Cyclone
26169,Green Tropical Cyclone DIANNE-25 in Australia ...,Green,1.0,Green,1.00,NaN,2025-03-28 00:00:00,2025-03-28 18:00:00,AUS,83 km/h,123.800,-16.200,Tropical Cyclone
26170,Green Tropical Cyclone ALVIN-25 in Mexico from...,Green,1.0,Green,1.00,NaN,2025-05-28 21:00:00,2025-05-31 15:00:00,MEX,93 km/h,-109.500,20.700,Tropical Cyclone
26171,Green Tropical Cyclone FLOSSIE-25 in Mexico fr...,Green,1.0,Green,1.00,NaN,2025-06-29 09:00:00,2025-07-03 21:00:00,-1,185 km/h,-112.400,21.200,Tropical Cyclone
26172,Green Tropical Cyclone BARRY-25 in Mexico from...,Green,1.0,Green,1.00,NaN,2025-06-28 21:00:00,2025-06-30 09:00:00,MEX,74 km/h,-99.200,23.000,Tropical Cyclone

In [412]:
drought = standardize_columns(drought)
earthquake = standardize_columns(earthquake)
eruption = standardize_columns(eruption)
flood = standardize_columns(flood)
forest_fires = standardize_columns(forest_fires)
tropical_cyclone = standardize_columns(tropical_cyclone)

print("Column names standardized successfully.")

Column names standardized successfully.

In [413]:
if "Unnamed: 0" in flood.columns:
    flood = flood.drop(columns=["Unnamed: 0"])

print(flood.columns.tolist())

['description', 'alertlevel', 'alertscore', 'episodealertlevel', 'episodealertscore', 'country', 'fromdate', 'todate', 'iso3', 'gdacs_id', 'longitude', 'latitude', 'disaster_type']

In [414]:
drought["disaster_type"] = "Drought"
earthquake["disaster_type"] = "Earthquake"
eruption["disaster_type"] = "Eruption"
flood["disaster_type"] = "Flood"
forest_fires["disaster_type"] = "Forest Fire"
tropical_cyclone["disaster_type"] = "Tropical Cyclone"

print("Disaster type added successfully.")

Disaster type added successfully.

In [415]:
master_columns = [
    "description",
    "alertlevel",
    "alertscore",
    "episodealertlevel",
    "episodealertscore",
    "country",
    "fromdate",
    "todate",
    "iso3",
    "gdacs_id",
    "longitude",
    "latitude",
    "disaster_type"
]

print("Master columns defined successfully.")

Master columns defined successfully.

In [416]:
def prepare_for_merge(df):
    df = df.copy()

    for column in master_columns:
        if column not in df.columns:
            df[column] = np.nan

    return df[master_columns]

In [417]:
drought = prepare_for_merge(drought)
earthquake = prepare_for_merge(earthquake)
eruption = prepare_for_merge(eruption)
flood = prepare_for_merge(flood)
forest_fires = prepare_for_merge(forest_fires)
tropical_cyclone = prepare_for_merge(tropical_cyclone)

print("All 6 datasets are ready to be combined.")

All 6 datasets are ready to be combined.

In [418]:
master_disaster_dataset = pd.concat(
    [
        drought,
        earthquake,
        eruption,
        flood,
        forest_fires,
        tropical_cyclone
    ],
    ignore_index=True
)

print("All 6 datasets combined successfully.")

All 6 datasets combined successfully.

In [419]:
print("Shape:", master_disaster_dataset.shape)

display(master_disaster_dataset.head())

Shape: (26173, 13)

,description,alertlevel,alertscore,episodealertlevel,episodealertscore,country,fromdate,todate,iso3,gdacs_id,longitude,latitude,disaster_type
0,"Green Drought in Germany, Denmark, France, Lat...",Green,1.0,NaN,0.25,"Germany, Denmark, France, Latvia, Poland, Sweden",2017-07-21,2019-02-09 15:07:00,DEU,DR 1012168,11.087,53.882,Drought
1,Green Drought in Uzbekistan from: 21 Nov 2017 ...,Green,1.0,NaN,0.75,Uzbekistan,2017-11-21,2018-09-06 09:57:00,UZB,DR 1012172,65.500,40.996,Drought
2,Green Drought in Brazil from: 21 Dec 2017 to:...,Green,1.0,NaN,0.50,Brazil,2017-12-21,2018-09-06 09:57:00,BRA,DR 1012174,-50.105,-21.917,Drought
3,Orange Drought in Australia from: 21 Feb 2018 ...,Orange,2.0,NaN,1.00,Australia,2018-02-21,2018-11-24 16:27:00,AUS,DR 1012191,144.500,-33.500,Drought
4,Orange Drought in Madagascar from: 21 Mar 2018...,Orange,2.0,NaN,1.50,Madagascar,2018-03-21,2018-09-13 13:57:00,MDG,DR 1012304,46.464,-19.498,Drought

In [420]:
print(master_disaster_dataset["disaster_type"].value_counts())

disaster_type
Earthquake          20290
Forest Fire          3051
Flood                2126
Tropical Cyclone      405
Drought               240
Eruption               61
Name: count, dtype: int64

In [421]:
master_disaster_dataset.to_csv(
    "master_disaster_dataset.csv",
    index=False
)

print("master_disaster_dataset.csv created successfully!")

master_disaster_dataset.csv created successfully!

In [422]:
print("Columns:")
print(master_disaster_dataset.columns.tolist())

print("\nMissing values:")
print(master_disaster_dataset.isnull().sum())

Columns:
['description', 'alertlevel', 'alertscore', 'episodealertlevel', 'episodealertscore', 'country', 'fromdate', 'todate', 'iso3', 'gdacs_id', 'longitude', 'latitude', 'disaster_type']

Missing values:
description              0
alertlevel               0
alertscore               0
episodealertlevel     3291
episodealertscore        0
country               2211
fromdate                 0
todate                   0
iso3                  1081
gdacs_id             20290
longitude                0
latitude                 0
disaster_type            0
dtype: int64

In [423]:
print("Missing values by disaster type:")
print(
    master_disaster_dataset
    .groupby("disaster_type")
    .apply(lambda x: x.isnull().sum())
)

Missing values by disaster type:
                  description  alertlevel  alertscore  episodealertlevel  \
disaster_type
Drought                     0           0           0                240
Earthquake                  0           0           0                  0
Eruption                    0           0           0                  0
Flood                       0           0           0                  0
Forest Fire                 0           0           0               3051
Tropical Cyclone            0           0           0                  0

                  episodealertscore  country  fromdate  todate  iso3  \
disaster_type
Drought                           0        0         0       0     0
Earthquake                        0     1806         0       0  1081
Eruption                          0        0         0       0     0
Flood                             0        0         0       0     0
Forest Fire                       0        0         0       0     0
Tropical Cyclone                  0      405         0       0     0

                  gdacs_id  longitude  latitude
disaster_type
Drought                  0          0         0
Earthquake           20290          0         0
Eruption                 0          0         0
Flood                    0          0         0
Forest Fire              0          0         0
Tropical Cyclone         0          0         0

In [424]:
print("Duplicate rows:", master_disaster_dataset.duplicated().sum())

Duplicate rows: 0

In [425]:
print(master_disaster_dataset.dtypes)

description              str
alertlevel               str
alertscore           float64
episodealertlevel     object
episodealertscore    float64
country               object
fromdate                 str
todate                   str
iso3                     str
gdacs_id              object
longitude            float64
latitude             float64
disaster_type            str
dtype: object

In [426]:
master_disaster_dataset["fromdate"] = pd.to_datetime(
    master_disaster_dataset["fromdate"],
    errors="coerce"
)

master_disaster_dataset["todate"] = pd.to_datetime(
    master_disaster_dataset["todate"],
    errors="coerce"
)

print(master_disaster_dataset[["fromdate", "todate"]].dtypes)

fromdate    datetime64[us]
todate      datetime64[us]
dtype: object

In [427]:
print("Missing fromdate:", master_disaster_dataset["fromdate"].isnull().sum())
print("Missing todate:", master_disaster_dataset["todate"].isnull().sum())

Missing fromdate: 22882
Missing todate: 3051

In [428]:
master_disaster_dataset["fromdate"] = pd.to_datetime(
    master_disaster_dataset["fromdate"],
    format="mixed",
    errors="coerce"
)

master_disaster_dataset["todate"] = pd.to_datetime(
    master_disaster_dataset["todate"],
    format="mixed",
    errors="coerce"
)

print("Missing fromdate:", master_disaster_dataset["fromdate"].isnull().sum())
print("Missing todate:", master_disaster_dataset["todate"].isnull().sum())

Missing fromdate: 22882
Missing todate: 3051

In [429]:
print(master_disaster_dataset["fromdate"].head(20))
print("\n--- TODATE ---")
print(master_disaster_dataset["todate"].head(20))

0    2017-07-21
1    2017-11-21
2    2017-12-21
3    2018-02-21
4    2018-03-21
5    2018-04-21
6    2018-04-21
7    2018-04-21
8    2018-05-21
9    2018-05-21
10   2018-05-21
11   2018-05-11
12   2018-05-21
13   2018-06-21
14   2018-06-21
15   2018-06-21
16   2018-06-21
17   2018-07-21
18   2018-07-21
19   2018-07-21
Name: fromdate, dtype: datetime64[us]

--- TODATE ---
0    2019-02-09 15:07:00
1    2018-09-06 09:57:00
2    2018-09-06 09:57:00
3    2018-11-24 16:27:00
4    2018-09-13 13:57:00
5    2018-11-24 16:27:00
6    2018-10-10 08:17:00
7    2018-08-29 15:17:00
8    2018-12-30 14:05:00
9    2018-10-28 15:37:00
10   2018-10-10 08:17:00
11   2018-10-10 08:17:00
12   2018-08-20 10:37:15
13   2019-02-16 15:47:00
14   2018-11-16 15:57:00
15   2018-10-10 08:17:00
16   2018-10-10 08:17:00
17   2019-01-26 17:07:00
18   2018-12-30 14:05:00
19   2018-11-24 16:27:00
Name: todate, dtype: datetime64[us]

In [430]:
print("\nFromdate data types:")
print(master_disaster_dataset["fromdate"].map(type).value_counts())

print("\nTodate data types:")
print(master_disaster_dataset["todate"].map(type).value_counts())

Fromdate data types:
fromdate
<class 'pandas.api.typing.NaTType'>    22882
<class 'pandas.Timestamp'>              3291
Name: count, dtype: int64

Todate data types:
todate
<class 'pandas.Timestamp'>             23122
<class 'pandas.api.typing.NaTType'>     3051
Name: count, dtype: int64

In [431]:
print("Drought fromdate:")
print(drought["fromdate"].head())

print("\nEarthquake fromdate:")
print(earthquake["fromdate"].head())

print("\nEruption fromdate:")
print(eruption["fromdate"].head())

print("\nFlood fromdate:")
print(flood["fromdate"].head())

print("\nForest Fire fromdate:")
print(forest_fires["fromdate"].head())

print("\nTropical Cyclone fromdate:")
print(tropical_cyclone["fromdate"].head())

Drought fromdate:
0    2017-07-21
1    2017-11-21
2    2017-12-21
3    2018-02-21
4    2018-03-21
Name: fromdate, dtype: str

Earthquake fromdate:
0    2000-01-19 00:00:00
1    2000-02-14 00:00:00
2    2000-02-03 00:00:00
3    2000-04-05 04:37:00
4    2000-05-04 04:21:00
Name: fromdate, dtype: str

Eruption fromdate:
0    2011-09-20 18:00:00
1    2011-10-28 09:48:00
2    2011-12-30 18:00:00
3    2012-01-30 07:31:00
4    2012-02-28 04:30:00
Name: fromdate, dtype: str

Flood fromdate:
0    2000-01-26 00:00:00
1    2000-01-28 00:00:00
2    2000-01-08 00:00:00
3    2000-01-01 00:00:00
4    2000-02-17 00:00:00
Name: fromdate, dtype: str

Forest Fire fromdate:
0    2021-02-23
1    2021-02-25
2    2021-02-25
3    2021-02-23
4    2021-02-23
Name: fromdate, dtype: str

Tropical Cyclone fromdate:
0    2008-04-28 06:00:00
1    2011-05-22 00:00:00
2    2011-07-28 06:00:00
3    2011-07-31 15:00:00
4    2011-07-26 00:00:00
Name: fromdate, dtype: str

In [432]:
drought = prepare_for_merge(drought)
earthquake = prepare_for_merge(earthquake)
eruption = prepare_for_merge(eruption)
flood = prepare_for_merge(flood)
forest_fires = prepare_for_merge(forest_fires)
tropical_cyclone = prepare_for_merge(tropical_cyclone)

In [433]:
master_disaster_dataset = pd.concat(
    [
        drought,
        earthquake,
        eruption,
        flood,
        forest_fires,
        tropical_cyclone
    ],
    ignore_index=True
)

In [434]:
master_disaster_dataset["fromdate"] = pd.to_datetime(
    master_disaster_dataset["fromdate"],
    format="mixed",
    errors="coerce"
)

master_disaster_dataset["todate"] = pd.to_datetime(
    master_disaster_dataset["todate"],
    format="mixed",
    errors="coerce"
)

In [435]:
print("Missing fromdate:", master_disaster_dataset["fromdate"].isnull().sum())
print("Missing todate:", master_disaster_dataset["todate"].isnull().sum())

Missing fromdate: 0
Missing todate: 0

In [436]:
print(master_disaster_dataset[["fromdate", "todate"]].dtypes)

fromdate    datetime64[us]
todate      datetime64[us]
dtype: object

In [437]:
master_disaster_dataset["year"] = master_disaster_dataset["fromdate"].dt.year

master_disaster_dataset["month"] = master_disaster_dataset["fromdate"].dt.month

master_disaster_dataset["duration_days"] = (
    master_disaster_dataset["todate"] -
    master_disaster_dataset["fromdate"]
).dt.total_seconds() / (24 * 60 * 60)

master_disaster_dataset["duration_days"] = master_disaster_dataset["duration_days"].round(2)

print("Date features created successfully.")

Date features created successfully.

In [438]:
display(
    master_disaster_dataset[
        ["fromdate", "todate", "year", "month", "duration_days"]
    ].head()
)

    fromdate              todate  year  month  duration_days
0 2017-07-21 2019-02-09 15:07:00  2017      7         568.63
1 2017-11-21 2018-09-06 09:57:00  2017     11         289.41
2 2017-12-21 2018-09-06 09:57:00  2017     12         259.41
3 2018-02-21 2018-11-24 16:27:00  2018      2         276.69
4 2018-03-21 2018-09-13 13:57:00  2018      3         176.58

In [439]:
master_disaster_dataset[
    [
        "alertscore",
        "episodealertscore",
        "longitude",
        "latitude",
        "year",
        "month",
        "duration_days"
    ]
].describe()

,alertscore,episodealertscore,longitude,latitude,year,month,duration_days
count,26173.000000,26173.000000,26173.000000,26173.000000,26173.000000,26173.000000,26173.000000
mean,1.031406,0.375748,31.276689,10.646761,2012.891300,6.498873,4.689610
std,0.202214,0.444964,109.969085,28.816074,6.652943,3.453348,28.490087
min,1.000000,-1.000000,-179.990000,-66.860000,2000.000000,1.000000,-1.000000
25%,1.000000,0.000000,-70.590000,-11.202900,2007.000000,3.000000,0.000000
50%,1.000000,0.500000,52.588300,9.738000,2013.000000,6.000000,0.000000
75%,1.000000,0.500000,128.460200,36.284800,2018.000000,10.000000,0.000000
max,3.000000,3.786233,180.000000,86.893200,2025.000000,12.000000,1056.000000

In [440]:
print("Negative duration:", (master_disaster_dataset["duration_days"] < 0).sum())
print("Zero duration:", (master_disaster_dataset["duration_days"] == 0).sum())
print("Duration > 365 days:", (master_disaster_dataset["duration_days"] > 365).sum())

Negative duration: 1
Zero duration: 20650
Duration > 365 days: 43

In [441]:
print("Negative duration record:")
print(
    master_disaster_dataset[
        master_disaster_dataset["duration_days"] < 0
    ][
        ["description", "disaster_type", "fromdate", "todate", "duration_days"]
    ]
)

print("\nDuration > 365 days:")
print(
    master_disaster_dataset[
        master_disaster_dataset["duration_days"] > 365
    ][
        ["description", "disaster_type", "fromdate", "todate", "duration_days"]
    ].head(20)
)

Negative duration record:
                                             description disaster_type  \
21658  GREEN Flood in Indonesia from: 24 Apr 2008 00 ...         Flood

        fromdate     todate  duration_days
21658 2008-04-24 2008-04-23           -1.0

Duration > 365 days:
                                           description disaster_type  \
0    Green Drought in Germany, Denmark, France, Lat...       Drought
33   Orange Drought in Belize, Guatemala, Honduras,...       Drought
38   Red Drought in Angola, Botswana, Mozambique, N...       Drought
39   Green Drought in Philippines from: 21 Oct 2018...       Drought
43   Green Drought in Cambodia, Laos, Myanmar, Thai...       Drought
49   Orange Drought in Bolivia, Brazil from: 21 Dec...       Drought
84   Orange Drought in Argentina from: 21 Jun 2019 ...       Drought
97   Green Drought in Canada, United States from: 2...       Drought
103  Green Drought in Mozambique from: 21 Mar 2020 ...       Drought
117  Green Drought in Brazil from: 21 Jul 2020  to:...       Drought
120  Green Drought in Armenia, Azerbaijan, Iran fro...       Drought
122  Green Drought in Cameroon, Nigeria from: 21 Se...       Drought
123  Green Drought in Angola from: 21 Sep 2020  to:...       Drought
125  Green Drought in Argentina, Chile from: 21 Oct...       Drought
126  Green Drought in Afghanistan, Kazakhstan, Taji...       Drought
127  Green Drought in Argentina, Chile from: 21 Oct...       Drought
128  Green Drought in Italy from: 21 Nov 2020  to: ...       Drought
140  Green Drought in Islamic Republic of Iran, Kyr...       Drought
146  Green Drought in Brazil from: 21 Jan 2022  to:...       Drought
147  Green Drought in Greece, Türkiye from: 21 Jan ...       Drought

      fromdate              todate  duration_days
0   2017-07-21 2019-02-09 15:07:00         568.63
33  2018-09-21 2020-03-03 14:37:00         529.61
38  2018-10-21 2020-03-24 16:37:00         520.69
39  2018-10-21 2020-01-06 14:47:00         442.62
43  2018-11-21 2020-10-20 00:00:00         699.00
49  2018-12-21 2020-08-10 15:27:00         598.64
84  2019-06-21 2020-12-30 00:00:00         558.00
97  2020-02-21 2022-02-09 00:00:00         719.00
103 2020-03-21 2021-04-30 00:00:00         405.00
117 2020-07-21 2021-10-17 00:00:00         453.00
120 2020-08-21 2021-11-07 00:00:00         443.00
122 2020-09-21 2021-12-13 00:00:00         448.00
123 2020-09-21 2021-12-05 00:00:00         440.00
125 2020-10-21 2023-06-19 00:00:00         971.00
126 2020-10-21 2022-09-28 00:00:00         707.00
127 2020-10-21 2022-05-30 00:00:00         586.00
128 2020-11-21 2021-12-13 00:00:00         387.00
140 2021-10-21 2024-07-03 00:00:00         986.00
146 2022-01-21 2023-07-12 00:00:00         537.00
147 2022-01-21 2023-06-19 00:00:00         514.00

In [442]:
master_disaster_dataset.loc[
    master_disaster_dataset["duration_days"] < 0,
    "duration_days"
] = 0

print("Negative duration after cleaning:",
      (master_disaster_dataset["duration_days"] < 0).sum())

Negative duration after cleaning: 0

In [443]:
print(
    "episodealertscore = -1:",
    (master_disaster_dataset["episodealertscore"] == -1).sum()
)

episodealertscore = -1: 614

In [444]:
print(
    master_disaster_dataset[
        master_disaster_dataset["episodealertscore"] == -1
    ]["disaster_type"].value_counts()
)

disaster_type
Earthquake    611
Flood           3
Name: count, dtype: int64

In [445]:
master_disaster_dataset["episodealertscore"] = (
    master_disaster_dataset["episodealertscore"]
    .replace(-1, np.nan)
)

print(
    "Missing episodealertscore:",
    master_disaster_dataset["episodealertscore"].isna().sum()
)

Missing episodealertscore: 614

In [446]:
missing_values = master_disaster_dataset.isnull().sum()

print(missing_values[missing_values > 0])

episodealertlevel     3291
episodealertscore      614
country               2211
iso3                  1081
gdacs_id             20290
dtype: int64

In [447]:
master_disaster_dataset = master_disaster_dataset.drop(
    columns=["gdacs_id"]
)

print(master_disaster_dataset.columns.tolist())

['description', 'alertlevel', 'alertscore', 'episodealertlevel', 'episodealertscore', 'country', 'fromdate', 'todate', 'iso3', 'longitude', 'latitude', 'disaster_type', 'year', 'month', 'duration_days']

In [448]:
print(
    master_disaster_dataset[
        master_disaster_dataset["episodealertlevel"].isna()
    ]["disaster_type"].value_counts()
)

disaster_type
Forest Fire    3051
Drought         240
Name: count, dtype: int64

In [449]:
master_disaster_dataset = master_disaster_dataset.drop(
    columns=["episodealertlevel"]
)

print(master_disaster_dataset.columns.tolist())

['description', 'alertlevel', 'alertscore', 'episodealertscore', 'country', 'fromdate', 'todate', 'iso3', 'longitude', 'latitude', 'disaster_type', 'year', 'month', 'duration_days']

In [450]:
print(
    master_disaster_dataset[
        master_disaster_dataset["country"].isna()
    ]["disaster_type"].value_counts()
)

disaster_type
Earthquake          1806
Tropical Cyclone     405
Name: count, dtype: int64

In [451]:
master_disaster_dataset["country"] = (
    master_disaster_dataset["country"].fillna("Unknown")
)

print(
    "Missing country:",
    master_disaster_dataset["country"].isna().sum()
)

Missing country: 0

In [452]:
print(
    master_disaster_dataset[
        master_disaster_dataset["iso3"].isna()
    ]["disaster_type"].value_counts()
)

disaster_type
Earthquake    1081
Name: count, dtype: int64

In [453]:
master_disaster_dataset["iso3"] = (
    master_disaster_dataset["iso3"].fillna("Unknown")
)

print(
    "Missing iso3:",
    master_disaster_dataset["iso3"].isna().sum()
)

Missing iso3: 0

In [454]:
missing_episode_score = master_disaster_dataset[
    master_disaster_dataset["episodealertscore"].isna()
]

print(
    missing_episode_score[
        [
            "disaster_type",
            "alertlevel",
            "alertscore",
            "episodealertscore"
        ]
    ].head(20)
)

      disaster_type alertlevel  alertscore  episodealertscore
559      Earthquake      Green         1.0                NaN
937      Earthquake      Green         1.0                NaN
1548     Earthquake      Green         1.0                NaN
1919     Earthquake      Green         1.0                NaN
1995     Earthquake      Green         1.0                NaN
2148     Earthquake      Green         1.0                NaN
2937     Earthquake      Green         1.0                NaN
3220     Earthquake      Green         1.0                NaN
3737     Earthquake      Green         1.0                NaN
4329     Earthquake      Green         1.0                NaN
4486     Earthquake      Green         1.0                NaN
4514     Earthquake      Green         1.0                NaN
4584     Earthquake      Green         1.0                NaN
4665     Earthquake      GREEN         1.0                NaN
6519     Earthquake      Green         1.0                NaN
7057     Earthquake      Green         1.0                NaN
7273     Earthquake      Green         1.0                NaN
8319     Earthquake      Green         1.0                NaN
10590    Earthquake      Green         1.0                NaN
11066    Earthquake      Green         1.0                NaN

In [455]:
print("Missing values:")
print(master_disaster_dataset.isnull().sum())

print("\nDuplicate rows:")
print(master_disaster_dataset.duplicated().sum())

Missing values:
description            0
alertlevel             0
alertscore             0
episodealertscore    614
country                0
fromdate               0
todate                 0
iso3                   0
longitude              0
latitude               0
disaster_type          0
year                   0
month                  0
duration_days          0
dtype: int64

Duplicate rows:
3

In [456]:
duplicates = master_disaster_dataset[
    master_disaster_dataset.duplicated(keep=False)
]

print(duplicates)

                                             description alertlevel  \
23786  Green Forest fires in Bolivia from: 29 Aug 202...      Green
23790  Green Forest fires in Bolivia from: 29 Aug 202...      Green
23996  Green Forest fires in Cote d'Ivoire from: 31 D...      Green
24001  Green Forest fires in Cote d'Ivoire from: 31 D...      Green
24164  Green Forest fires in Thailand from: 27 Feb 20...      Green
24169  Green Forest fires in Thailand from: 27 Feb 20...      Green

       alertscore  episodealertscore        country   fromdate     todate  \
23786         1.0                0.5        Bolivia 2022-08-29 2022-09-11
23790         1.0                0.5        Bolivia 2022-08-29 2022-09-11
23996         1.0                0.5  Cote d'Ivoire 2022-12-31 2023-01-11
24001         1.0                0.5  Cote d'Ivoire 2022-12-31 2023-01-11
24164         1.0                0.5       Thailand 2023-02-27 2023-03-14
24169         1.0                0.5       Thailand 2023-02-27 2023-03-14

      iso3   longitude   latitude disaster_type  year  month  duration_days
23786  BOL  -58.602971 -16.816460   Forest Fire  2022      8           13.0
23790  BOL  -58.602971 -16.816460   Forest Fire  2022      8           13.0
23996  CIV   -7.122875   7.973859   Forest Fire  2022     12           11.0
24001  CIV   -7.122875   7.973859   Forest Fire  2022     12           11.0
24164  THA  101.229812  17.155404   Forest Fire  2023      2           15.0
24169  THA  101.229812  17.155404   Forest Fire  2023      2           15.0

In [457]:
master_disaster_dataset = master_disaster_dataset.drop_duplicates(
    ignore_index=True
)

print("Duplicate rows after cleaning:",
      master_disaster_dataset.duplicated().sum())

print("Dataset shape:",
      master_disaster_dataset.shape)

Duplicate rows after cleaning: 0
Dataset shape: (26170, 14)

In [458]:
print(master_disaster_dataset["alertlevel"].value_counts(dropna=False))

alertlevel
Green     21466
GREEN      3994
Orange      349
ORANGE      197
Red          96
RED          41
green        25
orange        2
Name: count, dtype: int64

In [459]:
master_disaster_dataset["alertlevel"] = (
    master_disaster_dataset["alertlevel"].str.strip().str.title()
)

print(master_disaster_dataset["alertlevel"].value_counts())

alertlevel
Green     25485
Orange      548
Red         137
Name: count, dtype: int64

In [460]:
print(master_disaster_dataset["disaster_type"].value_counts())

disaster_type
Earthquake          20290
Forest Fire          3048
Flood                2126
Tropical Cyclone      405
Drought               240
Eruption               61
Name: count, dtype: int64

In [461]:
print(
    "Duplicate descriptions:",
    master_disaster_dataset["description"].duplicated().sum()
)

Duplicate descriptions: 829

In [462]:
repeated_descriptions = master_disaster_dataset[
    master_disaster_dataset["description"].duplicated(keep=False)
]

print(
    repeated_descriptions[
        [
            "description",
            "disaster_type",
            "country",
            "fromdate",
            "todate",
            "latitude",
            "longitude"
        ]
    ].head(20)
)

                                             description disaster_type  \
12075  Green M 4.8 Earthquake in United States at: 29...    Earthquake
12076  Green M 4.8 Earthquake in United States at: 29...    Earthquake
16687  Green M 4.5 Earthquake in Somalia at: 28 Jul 2...    Earthquake
16688  Green M 4.5 Earthquake in Somalia at: 28 Jul 2...    Earthquake
19023  Green M 4.7 Earthquake in Tonga at: 28 Mar 202...    Earthquake
19024  Green M 4.7 Earthquake in Tonga at: 28 Mar 202...    Earthquake
19161  Green M 5 Earthquake in South Georgia and the ...    Earthquake
19162  Green M 5 Earthquake in South Georgia and the ...    Earthquake
21114  GREEN Flood in Peru from: 28 Jan 2003 00 to: 1...         Flood
21115  GREEN Flood in Peru from: 28 Jan 2003 00 to: 1...         Flood
21140  GREEN Flood in Australia from: 21 Feb 2003 00 ...         Flood
21141  GREEN Flood in Australia from: 21 Feb 2003 00 ...         Flood
21542  GREEN Flood in China from: 28 Jun 2006 00 to: ...         Flood
21543  GREEN Flood in China from: 28 Jun 2006 00 to: ...         Flood
21554  GREEN Flood in USA from: 27 Jul 2006 00 to: 27...         Flood
21555  GREEN Flood in USA from: 27 Jul 2006 00 to: 27...         Flood
21693  GREEN Flood in USA from: 26 Dec 2008 00 to: 26...         Flood
21694  GREEN Flood in USA from: 26 Dec 2008 00 to: 26...         Flood
21919  GREEN Flood in USA from: 25 May 2013 00 to: 03...         Flood
21920  GREEN Flood in USA from: 25 May 2013 00 to: 03...         Flood

                                            country            fromdate  \
12075                                 United States 2013-05-29 14:38:03
12076                                 United States 2013-05-29 14:38:03
16687                                       Somalia 2017-07-28 03:54:41
16688                                       Somalia 2017-07-28 03:54:41
19023                                         Tonga 2020-03-28 15:11:39
19024                                         Tonga 2020-03-28 15:11:39
19161  South Georgia and the South Sandwich Islands 2020-05-28 08:37:57
19162  South Georgia and the South Sandwich Islands 2020-05-28 08:37:57
21114                                          Peru 2003-01-28 00:00:00
21115                                          Peru 2003-01-28 00:00:00
21140                                     Australia 2003-02-21 00:00:00
21141                                     Australia 2003-02-21 00:00:00
21542                                         China 2006-06-28 00:00:00
21543                                         China 2006-06-28 00:00:00
21554                                           USA 2006-07-27 00:00:00
21555                                           USA 2006-07-27 00:00:00
21693                                           USA 2008-12-26 00:00:00
21694                                           USA 2008-12-26 00:00:00
21919                                           USA 2013-05-25 00:00:00
21920                                           USA 2013-05-25 00:00:00

                   todate  latitude  longitude
12075 2013-05-29 14:38:03   34.4125  -119.9260
12076 2013-05-29 14:38:03   34.4125  -119.9260
16687 2017-07-28 03:54:41   13.2518    50.7929
16688 2017-07-28 03:54:41   13.2500    50.7900
19023 2020-03-28 15:11:39  -21.0731  -173.8681
19024 2020-03-28 15:11:39  -21.0700  -173.8700
19161 2020-05-28 08:37:57  -56.2715   -27.1608
19162 2020-05-28 08:37:57  -56.2700   -27.1600
21114 2003-02-10 23:59:59  -13.2390   -72.1020
21115 2003-02-10 23:59:59  -15.8740   -69.3100
21140 2003-02-24 23:59:59  -18.2290   127.8570
21141 2003-02-24 23:59:59  -32.5900   149.7000
21542 2006-06-28 00:00:00   28.4700   105.7300
21543 2006-06-28 00:00:00   34.0400   117.0300
21554 2006-07-27 00:00:00   31.7560  -106.3910
21555 2006-07-27 00:00:00   41.5190   -81.0920
21693 2008-12-26 00:00:00   44.6560  -123.5240
21694 2008-12-26 00:00:00   -3.3300   103.1390
21919 2013-06-03 23:59:59   37.0890   -91.6350
21920 2013-06-03 23:59:59   41.9210   -93.3870

In [463]:
print(
    master_disaster_dataset["country"]
    .value_counts()
    .head(30)
)

country
Indonesia                           2514
Unknown                             2211
Japan                               1423
United States                       1244
Papua New Guinea                     851
Chile                                846
Greece                               777
Philippines                          650
China                                648
Russian Federation                   623
Tonga                                623
Russia                               606
Australia                            570
India                                534
Mexico                               526
Vanuatu                              474
Türkiye                              468
Peru                                 397
Canada                               355
Fiji                                 341
Argentina                            280
Brazil                               238
New Zealand                          208
Myanmar                              208
The Democratic Republic of Congo     188
Angola                               176
Iran                                 176
Colombia                             175
Solomon Islands                      171
Sudan                                169
Name: count, dtype: int64

In [464]:
print(
    sorted(
        master_disaster_dataset["country"].dropna().unique()
    )
)

[' Iran', '-1', 'Afghanistan', 'Afghanistan, Iran, Pakistan', 'Afghanistan, Iran, Pakistan, Tajikistan', 'Afghanistan, Islamic Republic of Iran, Kyrgyzstan, Kazakhstan, Pakistan, Tajikistan, Turkmenistan, Uzbekistan', 'Afghanistan, Israel, Iraq, Islamic Republic of Iran, Jordan, Kyrgyzstan, Kazakhstan, Lebanon, Pakistan, Gaza Strip, Syria, Tajikistan, Turkmenistan, Türkiye, Uzbekistan', 'Afghanistan, Kazakhstan, Tajikistan, Turkmenistan', 'Afghanistan, Pakistan, Tajikistan', 'Afghanistan-Tajikistan Bord Reg.', 'Afghanistan\xa0', 'Africa', 'Alaska', 'Alaska Peninsula', 'Albania', 'Albania, Austria, Bosnia & Herzegovina, Belgium, Bulgaria, Switzerland, Czech Republic, Germany, France, Croatia, Hungary, Italy, Liechtenstein, Luxembourg, Montenegro, The Republic of North Macedonia, Netherlands, Poland, Romania, Serbia, Slovenia, Slovakia, Ukraine, ', 'Albania, Austria, Bosnia & Herzegovina, Bulgaria, Belarus, Greece, Croatia, Hungary, Kazakhstan, Moldova, Montenegro, Macedonia, Romania, Serbia, Russia, Slovenia, Slovakia, Türkiye, Ukraine', 'Albania, Bulgaria, Greece, The Republic of North Macedonia, Türkiye', 'Albania, North Macedonia', 'Algeria', 'Algeria, Morocco', 'Algeria, Morocco, Tunisia', 'Algeria, Spain, Morocco', 'Algeria\xa0', 'American Samoa', 'Andaman Islands, India Region', 'Andreanof Islands, Aleutian Is.', 'Angola', 'Angola, Botswana, Mozambique, Namibia, Zambia, Zimbabwe', 'Angola, Democratic Republic of Congo, Republic of Congo', 'Angola, Democratic Republic of Congo, Zambia', 'Angola, The Democratic Republic of Congo', 'Angola\xa0', 'Anguilla', 'Anguilla|Antigua and Barbuda|British Virgin Islands|Cuba|Dominican Republic|Puerto Rico|Saint Kitts and Nevis|Saint-Martin (French part)|Turks and Caicos Islands|United States of America|United States Virgin Islands', 'Antarctica', 'Antigua & Barbuda', 'Antigua and Barbuda', 'Argentina', 'Argentina, Brazil, Paraguay', 'Argentina, Chile', 'Argentina, Paraguay', 'Argentina|Paraguay', 'Armenia, Azerbaijan, Iran', 'Aru Islands Region, Indonesia', 'Aruba', 'Ascension Island Region', 'Auckland Islands, N.Z.  Region', 'Australia', 'Australia\xa0', 'Austria', 'Austria, Belgium, Czech Republic, Germany, Denmark, France, Luxembourg, Netherlands, Poland, Sweden', 'Austria, Belgium, Switzerland, Germany, France, Liechtenstein, Luxembourg', 'Azerbaijan', 'Azerbaijan, Russia', 'Bali Sea', 'Balleny Islands Region', 'Banda Sea', 'Bangladesh', 'Bangladesh, India', 'Bangladesh, India, Myanmar', 'Bangladesh, India, Myanmar, Nepal', 'Bangladesh, Myanmar', 'Bangladesh\xa0', 'Barbados', 'Belarus', 'Belarus, Estonia, Lithuania, Latvia, Poland, Russia, Ukraine', 'Belarus\xa0', 'Belgium, Czech Republic, Germany, France, Luxembourg, Poland, Sweden, ', 'Belgium, Switzerland, Czech Republic, Germany, France, Luxembourg, Netherlands, Poland', 'Belgium, Switzerland, Germany, France, Luxembourg, Netherlands', 'Belize', 'Belize, Guatemala, Honduras, Mexico', 'Belize, Guatemala, Honduras, Mexico, Nicaragua', 'Belize, Guatemala, Mexico', 'Benin', 'Benin, Burkina Faso', 'Benin, Niger', 'Bhutan', 'Bhutan, China, India, Myanmar', 'Bhutan, China, India, Nepal', 'Bismarck Sea', 'Bolivia', 'Bolivia, Brazil', 'Bolivia, Brazil, Peru, Paraguay', 'Bolivia\xa0', 'Bonin Islands, Japan Region', 'Borneo', 'Bosnia & Herzegovina', 'Bosnia and Herzegovina', 'Bosnia-Herzegovina', 'Botswana', 'Botswana, Lesotho, Mozambique, Swaziland, South Africa', 'Botswana, Mozambique, South Africa, Zimbabwe', 'Brazil', 'Brazil\xa0', 'Brazil\xa0\xa0', 'British Indian Ocean Territory', 'British Virgin Is.', 'British Virgin Islands', 'British Virgin Islands, The Bahamas', 'Bulgaria', 'Bulgaria, Iraq, Iran, Türkiye', 'Bulgaria, Moldova, Romania, Türkiye, Ukraine', 'Burkina Faso', 'Burkina Faso, Benin', 'Burkina Faso, Benin, Central African Republic, Cameroon, Niger, Nigeria, Chad', 'Burkina Faso, Mali', 'Burma', 'Burma (Myanmar)', 'Burma/Myanmar', 'Burundi', 'Burundi, Democratic Republic of Congo, Rwanda', 'Camaroun', 'Cambodia', 'Cambodia, Laos, Myanmar, Thailand, Vietnam', 'Cambodia, Laos, Thailand, Vietnam', 'Cambodia, Viet Nam', 'Cambodia,\xa0Vietnam, Thailand and Laos', 'Cambodia\xa0', 'Cameroon', 'Cameroon, Equatorial Guinea', 'Cameroon, Nigeria', 'Cameroon\xa0', 'Canada', 'Canada and USA', 'Canada, United States', 'Canada\xa0', 'Canary Islands', 'Cape Verde', 'Carlsberg Ridge', 'Cayman Islands', 'Central African Republic', 'Central African Republic, Cameroon', 'Central African Republic, Chad', 'Central African Republic, Sudan', 'Central African Republic, The Democratic Republic of Congo', 'Central Alaska', 'Central East Pacific Rise', 'Central Mediterranean Sea', 'Central Mid-Atlantic Ridge', 'Central Peru', 'Chad', 'Chad, Cameroon', 'Chad\xa0', 'Chagos Archipelago Region', 'Chile', 'Chile-Argentina Border Region', 'Chile-Bolivia Border Region', 'Chile-C', 'Chile-S', 'China', 'China, India, Myanmar, Nepal', 'China, India, Nepal', 'China, Laos, Myanmar, Thailand', 'China, Malaysia, Philippines, Thailand', 'China, Mongolia', 'China, North Korea, South Korea', 'China\xa0', 'Christmas I.', 'Christmas Island', 'Cocos (Keeling) Islands', 'Cocos Is.', 'Colombia', 'Colombia, Venezuela', 'Colombia\xa0', 'Columbia', 'Columbia\xa0', 'Comoros', 'Comoros Islands', 'Congo', 'Congo Republic', 'Congo, DRC', 'Congo, DRC, Central African Republic, Kenya, South Sudan, Uganda', 'Congo, The Democratic Republic of the', 'Congo-Brazzaville', 'Cook Is.', 'Cook Islands', 'Cook Strait, New Zealand', 'Costa Rica', "Cote d'Ivoire", 'Crete, Greece', 'Croatia', 'Croatia, Hungary, Romania, Serbia', 'Cuba', 'Cuba|United States of America', 'Cuba\xa0', 'Cyprus', 'Czech Republic', 'DR Congo', 'DR Congo\xa0', 'Democratic Republic Of Congo', 'Democratic Republic of Congo', 'Democratic Republic of Congo, Central African Republic, Republic of Congo, Cameroon, Gabon, Equatorial Guinea', 'Democratic Republic of Congo, Zambia', 'Democratic Republic of the Congo', 'Denmark, Germany', 'Djibouti', 'Dodecanese Islands, Greece', 'Dominica', 'Dominican Republic', 'Dominican Republic, Haiti', 'Drake Passage', 'E. Caroline Islands, Micronesia', 'East Of North Island, N.Z.', 'East Of South Sandwich Islands', 'East Timor', 'East Timor\xa0', 'Easter Island Region', 'Eastern Caucasus', 'Eastern Greenland', 'Eastern India\xa0', 'Eastern New Guinea Reg., P.N.G.', 'Eastern Russia\xa0', 'Eastern Sea Of Japan', 'Eastern Siberia, Russia', 'Ecuador', 'Ecuador\xa0', 'Egypt', 'El Salvador', 'El Salvador\xa0', 'Error: .NET Framework execution was aborted by escalation policy because of out of memory. ', 'Eswatini, Madagascar, Mozambique, South Africa, Zimbabwe', 'Ethiopia', 'Ethiopia, Sudan', 'Ethiopia, Sudan, South Sudan', 'Ethiopia\xa0', 'Europe', 'Falkland Islands (Malvinas)', 'Faroe Is.', 'Faroe Islands', 'Federated States of Micronesia', 'Fiji', 'Fiji Islands Region', 'Finland', 'Flores Region, Indonesia', 'Flores Sea', 'Former Yugoslav Republic of Macedonia', 'Fox Islands, Aleutian Islands', 'France', 'France, Italy', 'France, Italy, Monaco', 'France, United Kingdom', 'France\xa0', 'French Polynesia', 'French Southern & Antarctic Lands', 'French Southern and Antarctic Lands', 'Gabon', 'Galapagos Triple Jungtion Region', 'Georgia', 'Germany', 'Germany, Denmark, France, Latvia, Poland, Sweden', 'Ghana', 'Ghana, Burkina Faso', 'Ghana\xa0', 'Glorioso Is.', 'Greece', 'Greece, Türkiye', 'Greece,Türkiye', 'Greenland', 'Greenland Sea', 'Grenada', 'Guadeloupe', 'Guam', 'Guatamala', 'Guatemala', 'Guatemala, Mexico', 'Guatemala\xa0', 'Guinea', "Guinea, Cote d'Ivoire", 'Guinea, Sierra Leone', 'Guinea-Bissau', 'Guinea-Bissau, Senegal', 'Gulf Of California', 'Guyana', 'Haiti', 'Haiti\xa0', 'Halmahera, Indonesia', 'Halmahera-Indonesia', 'Hawaii', 'Hindu Kush Region, Afghanistan', 'Hokkaido, Japan  Region', 'Honduras', 'Hungary', 'Iceland', 'Iceland Region', 'India', 'India, Myanmar', 'India, Pakistan', 'India, Sri Lanka', 'India-Bangladesh Border Region', 'Indian Ocean Triple Junction', 'India\xa0', 'Indonesia', 'Indonesia \xa0', 'Indonesia, Malaysia', 'Indonesia\xa0', 'Indonesia\xa0\xa0', 'Iran', 'Iran, Iraq, Kuwait', 'Iran, Islamic Republic of', 'Iran-Iraq Border Region', 'Iran\xa0', 'Iraq', 'Iraq, Islamic Republic of Iran, Turkmenistan', 'Ireland', 'Ireland, , ', 'Ireland, United Kingdom', 'Irian Jaya Region, Indonesia', 'Irian Jaya, Indonesia', 'Islamic Republic of Iran', 'Islamic Republic of Iran, Kazakhstan, Turkmenistan, Uzbekistan', 'Islamic Republic of Iran, Kyrgyzstan, Kazakhstan, Tajikistan, Turkmenistan, Uzbekistan', 'Isle of Man, United Kingdom', 'Israel', 'Israel\xa0', 'Italy', 'Italy, ', 'Ivory Coast\xa0', 'Jamaica', 'Jan Mayen', 'Jan Mayen Island Region', 'Japan', 'Java, Indonesia', 'Juan De Nova I.', 'Kamchatka', 'Kamchatka Peninsula, Russia', 'Kazahkstan', 'Kazakhstan', 'Kazakhstan, Russia', 'Kazakhstan, Russia, Uzbekistan', 'Kazakhstan, Russian Federation', 'Kenya', 'Kenya, Somalia', 'Kenya\xa0', 'Kermadec Islands Region', 'Kermadec Islands, New Zealand', 'Komandorsky Islands Region', "Korea, Democratic People's Republic of", 'Kuril Is', 'Kuril Islands', 'Kuwait, Oman, United Arab Emirates', 'Kyrgyzstan', 'Kyrgyzstan, Kazakhstan, Tajikistan, Uzbekistan', 'Kyushu, Japan', 'Laos', 'Laos, Cambodia', 'Laos, Thailand', 'Laptev Sea', 'Latvia', 'Lebanon', 'Leeward Islands', 'Lesotho', 'Lesotho, South Africa', 'Liberia', "Liberia, Cote d'Ivoire", 'Liberia, Guinea', 'Libya', 'Line Islands Region, Kiribati', 'Lithuania', 'Luzon, Philippines', 'Macedonia', 'Madagascar', 'Malawi', 'Malawi\xa0', 'Malaysia', 'Malaysia \xa0', 'Malaysia\xa0', 'Maldives', 'Mali', 'Malta', 'Mariana Is-C Pacific', 'Mariana Islands', 'Mariana Islands Region', 'Martinique', 'Mauritania', 'Mauritania, Senegal', 'Mauritius', 'Mauritius - Reunion Region', 'Mayotte', 'Mexico', 'Mexico, United States', 'Mexico\xa0', 'Mid-Indian Ridge', 'Minahassa Peninsula, Sulawesi', 'Mindanao, Philippines', 'Mindoro, Philippines', 'Miscellaneous (French) Indian Ocean Islands', 'Moldova', 'Moldova, Russia, Ukraine', 'Mongolia', 'Mongolia, Russia', 'Montenegro', 'Morocco', 'Mozambique', 'Mozambique, Zambia, Zimbabwe', 'Mozambique, Zimbabwe', 'Mozambique\xa0', 'Myanmar', 'Myanmar, Thailand', 'Myanmar, Union of', 'Myanmar-China Border Region', 'Myanmar-India Border Region', 'México', 'Namibia', 'Namibia, Botswana', 'Near Coast Of Central Chile', 'Near Coast Of Chiapas, Mexico', 'Near Coast Of Ecuador', 'Near Coast Of Guatemala', 'Near Coast Of Guerrero, Mexico', 'Near Coast Of Jalisco, Mexico', 'Near Coast Of Nicaragua', 'Near Coast Of Northern Chile', 'Near Coast Of Oaxaca, Mexico', 'Near Coast Of Oregon', 'Near Coast Of Peru', 'Near Coast Of Venezuela', 'Near East Coast Of Honshu, Japan', 'Near East Coast Of Kamchatka', 'Near N Coast Of New Guinea, Png.', 'Near N. Coast Of Eastern Siberia', 'Near North Coast Of Irian Jaya', 'Near S. Coast Of Honshu, Japan', 'Near S. Coast Of Western Honshu', 'Nepal', 'Nepal\xa0', 'New Britain Region, P.N.G.', 'New Caledonia', 'New Guinea, Papua New Guinea', 'New Guinea-NE of', 'New Ireland Region, P.N.G.', 'New Zealand', 'Nicaragua', 'Nicaragua\xa0', 'Nicobar Islands, India Region', 'Niger', 'Niger, Benin', 'Nigeria', 'Nigeria\xa0', 'Niue', 'North Atlantic Ocean', 'North Indian Ocean', 'North Island, New Zealand', 'North Korea', 'North Korea\xa0', 'North Of Ascension Island', 'North Of Franz Josef Land', 'North Of Macquarie Island', 'North Of Severnaya Zemlya', 'North Of Svalbard', 'Northern Alaska', 'Northern Algeria', 'Northern And Central Iran', 'Northern Bangladesh\xa0and Eastern India', 'Northern Chile', 'Northern Colombia', 'Northern East Pacfic Rise', 'Northern Mariana Is.', 'Northern Mariana Islands', 'Northern Mid-Atlantic Ridge', 'Northern Molucca Sea', 'Northern Philippines, Central Japan and Taiwan - Typhoons Kirogi, Edeng and Kai Tak', 'Northern Sumatera, Indonesia', 'Northern Territory, Australia', 'Northern Türkiye', 'Northwest Of Ryukyu Islands', 'Northwestern Balkan Region', 'Northwestern D R Congo\xa0', 'Northwestern Kashmir', 'Norway', 'Norwegian Sea', 'Null', 'Off Coast Of Central America', 'Off Coast Of Central Chile', 'Off Coast Of Costa Rica', 'Off Coast Of Northern California', 'Off Coast Of Oregon', 'Off Coast Of Peru', 'Off Coast Of Southern Chile', 'Off E. Coast Of N. Island, N.Z.', 'Off East Coast Of Honshu, Japan', 'Off East Coast Of Kamchatka', 'Off W Coast Of Northern Sumatera', 'Oman', 'Oman, United Arab Emirates', 'Pacific-Antarctic Ridge', 'Pakistan', 'Pakistan\xa0', 'Palau', 'Palestine', 'Panama', 'Panama-Colombia Border Region', 'Papua New Guinea', 'Papua New Gunea', 'Paraguay', 'Paraguay, Argentina', 'Peru', 'Peru-Brazil Border Region', 'Peru\xa0', 'Philippine Islands Region', 'Philippines', 'Philippines\xa0', 'Phillipines', 'Poland', 'Poland\xa0', 'Portugal', 'Portugal, Spain', 'Portugal\xa0', "Primor'ye, Russia", 'Prince Edward Islands Region', 'Puerto Rico', 'Qatar', 'Republic of Congo', 'Republic of Korea', 'Reykjanes Ridge', 'Romania', 'Russa', 'Russia', 'Russia, Ukraine', 'Russian Fed.', 'Russian Federation', 'Russian Federation, China', 'Rwanda', 'Rwanda\xa0', 'Ryukyu Islands, Japan', 'Saint Lucia, Saint Vincent and the Grenadines', 'Saint Vincent', 'Salta Province, Argentina', 'Samoa', 'San Juan Province, Argentina', 'Santa Cruz Islands', 'Santiago Del Estero Prov., Arg.', 'Saudi Arabia', 'Saudi Arabia\xa0', 'Scotia Sea', 'Senegal', 'Senegal, Gambia', 'Serbia', 'Serbia & Montenegro', 'Serbia and Montenegro', 'Serbia-Montenegro', 'Seychelles', 'Sierra Leone', 'Slovakia', 'Slovenia', 'Solomon Is.', 'Solomon Islands', 'Somalia', 'Somalia\xa0', 'South Africa', 'South Africa\xa0', 'South Atlantic Ocean', 'South Georgia & the South Sandwich Is.', 'South Georgia / South Sandwich Islands', 'South Georgia and the South Sandwich Islands', 'South Indian Ocean', 'South Korea', 'South Korea\xa0', 'South Of Africa', 'South Of Alaska', 'South Of Fiji Islands', 'South Of Java, Indonesia', 'South Of Kermadec Islands', 'South Of Mariana Islands', 'South Of Panama', 'South Of Tonga Islands', 'South Pacific Ocean', 'South Sandwich Islands Region', 'South Shetland Islands', 'South Sudan', 'Southeast Indian Ridge', 'Southeast Of Easter Island', 'Southeast Of Honshu, Japan', 'Southeast Of Loyalty Islands', 'Southeastern Alaska', 'Southeastern Brazil\xa0\xa0', 'Southeastern Siberia, Russia', 'Southern Alaska', 'Southern Argentina', 'Southern Bolivia', 'Southern East Pacific Rise', 'Southern Iran', 'Southern Italy', 'Southern Mid-Atlantic Ridge', 'Southern Peru', 'Southern Somalia\xa0', 'Southern Sumatera, Indonesia', 'Southern Xinjiang, China', 'Southwest Indian Ridge', 'Southwest Of Sumatera, Indonesia', 'Southwestern Pakistan', 'Southwestern Ryukyu Isl., Japan', 'Spain', 'Spain, Portugal', 'Spain\xa0', 'Sri Lanka', 'Sri Lanka\xa0', 'St. Helena', 'St. Vincent & the Grenadines', 'Strait Of Gibraltar', 'Sudan', 'Sudan and Eritrea', 'Sudan, Central African Republic', 'Sudan, Ethiopia', 'Sudan, The Democratic Republic of Congo', 'Sumatra', 'Sumbawa Region, Indonesia', 'Sunda Strait, Indonesia', 'Suriname', 'Svalbard', 'Svalbard and Jan Mayen', 'Sweden', 'Switzerland', 'Syria', 'Syrian Arab Republic', 'São Tomé and Príncipe', 'Taiwan', 'Taiwan Region', 'Tajikistan', 'Talaud Islands, Indonesia', 'Tanimbar Islands Reg., Indonesia', 'Tanzania', 'Tanzania, Mozambique', 'Tanzania, Uganda', 'Tanzania\xa0', 'Tasmania', 'Texas', 'Thailand', 'Thailand, Laos', 'Thailand, Myanmar', 'Thailand\xa0', 'The Bahamas', 'The Bahamas, Belize, Cuba, Guatemala, Mexico', 'The Democratic Republic of Congo', 'The Democratic Republic of Congo, Angola', 'The Democratic Republic of Congo, Central African Republic', 'The Democratic Republic of Congo, Sudan', 'The Democratic Republic of Congo, Zambia', 'The Gambia, Guinea, Guinea-Bissau, Senegal', 'Timor', 'Timor Leste', 'Timor Region', 'Timor-Leste', 'Togo', 'Tonga', 'Tonga Islands', 'Tonga Islands Region', 'Trinidad', 'Trinidad & Tobago', 'Trinidad & Tobago, Venezuela', 'Trinidad and Tobago', 'Trinidad and Tobago, United States', 'Tunisia', 'Turkmenistan', 'Turkmenistan-Iran Border Region', 'Turks and Caicos Islands', 'Türkiye', 'Türkiye\xa0', 'UK', 'UK and Ireland', 'UK\xa0', 'USA', 'USA.', 'USA\xa0', 'Uganda', 'Uganda\xa0', 'Ukraine', 'United Kingdom', 'United States', 'United States of America', 'United States, Canada', 'Unknown', 'Uruguay', 'Uruguay,', 'Uruguay\xa0', 'Uzbekistan', 'Vancouver Island, Canada Region', 'Vanuatu', 'Vanuatu Islands', 'Vanuatu Islands Region', 'Vanuatu-SW Pacific', 'Venezuela', 'Venezuela\xa0', 'Venezulea', 'Viet Nam', 'Vietnam', 'Vietnam\xa0', 'Virgin Is.', 'Virgin Islands', 'Virgin Islands  British', 'Virgin Islands  U.S.', 'Virgin Islands, British', 'Virgin Islands, U.S.', 'Volcano Islands, Japan Region', 'W Indies', 'W. Caroline Islands, Micronesia', 'Wallis & Futuna', 'Wallis and Futuna', 'West Chile Rise', 'West Of Galapagos Islands', 'West Of Macquarie Island', 'Western Brazil', 'Western India', 'Western Indian-Antarctic Ridge', 'Western Sahara', 'Western Texas', 'Xizang', 'Yemen', 'Yemen ', 'Yemen\xa0', 'Yemen\xa0\xa0', 'Yugoslavia', 'Zambia', 'Zambia, Angola', 'Zambia, The Democratic Republic of Congo', 'Zambia\xa0', 'Zimbabwe', 'Zimbabwe\xa0', 'Zimbawe']

In [465]:
invalid_country_values = [
    "-1",
    "Null",
    "Unknown"
]

print(
    master_disaster_dataset[
        master_disaster_dataset["country"].isin(invalid_country_values)
    ]["country"].value_counts()
)

country
Unknown    2211
Null          1
-1            1
Name: count, dtype: int64

In [466]:
master_disaster_dataset["country"] = (
    master_disaster_dataset["country"]
    .replace({
        "Null": "Unknown",
        "-1": "Unknown"
    })
)

print(master_disaster_dataset["country"].value_counts().head(10))

country
Indonesia             2514
Unknown               2213
Japan                 1423
United States         1244
Papua New Guinea       851
Chile                  846
Greece                 777
Philippines            650
China                  648
Russian Federation     623
Name: count, dtype: int64

In [467]:
country_counts = master_disaster_dataset["country"].value_counts()

print("Total unique country values:", country_counts.nunique())

print("\nCountries with very few records:")
print(country_counts[country_counts <= 3].to_string())

Total unique country values: 97

Countries with very few records:
country
Cambodia, Laos, Thailand, Vietnam                                                                                                                                                                                                                                                3
Central African Republic, Chad                                                                                                                                                                                                                                                   3
Afghanistan, Iran, Pakistan                                                                                                                                                                                                                                                      3
Colombia, Venezuela                                                                                                                                                                                                                                                              3
Spain, Portugal                                                                                                                                                                                                                                                                  3
Lesotho, South Africa                                                                                                                                                                                                                                                            3
Algeria, Morocco                                                                                                                                                                                                                                                                 3
Cameroon, Nigeria                                                                                                                                                                                                                                                                3
Ethiopia, Sudan, South Sudan                                                                                                                                                                                                                                                     3
Near S. Coast Of Honshu, Japan                                                                                                                                                                                                                                                   3
Trinidad and Tobago                                                                                                                                                                                                                                                              3
Off East Coast Of Honshu, Japan                                                                                                                                                                                                                                                  3
The Bahamas                                                                                                                                                                                                                                                                      3
Cocos (Keeling) Islands                                                                                                                                                                                                                                                          3
Seychelles                                                                                                                                                                                                                                                                       3
St. Helena                                                                                                                                                                                                                                                                       3
Juan De Nova I.                                                                                                                                                                                                                                                                  3
Antigua & Barbuda                                                                                                                                                                                                                                                                3
Timor Leste                                                                                                                                                                                                                                                                      3
Montenegro                                                                                                                                                                                                                                                                       3
Greenland Sea                                                                                                                                                                                                                                                                    3
South Atlantic Ocean                                                                                                                                                                                                                                                             3
Philippine Islands Region                                                                                                                                                                                                                                                        3
Tunisia                                                                                                                                                                                                                                                                          3
Banda Sea                                                                                                                                                                                                                                                                        3
Myanmar-India Border Region                                                                                                                                                                                                                                                      3
Serbia                                                                                                                                                                                                                                                                           3
Xizang                                                                                                                                                                                                                                                                           3
Eastern Siberia, Russia                                                                                                                                                                                                                                                          3
Sunda Strait, Indonesia                                                                                                                                                                                                                                                          3
North Island, New Zealand                                                                                                                                                                                                                                                        3
Flores Sea                                                                                                                                                                                                                                                                       3
Southern Xinjiang, China                                                                                                                                                                                                                                                         3
Off W Coast Of Northern Sumatera                                                                                                                                                                                                                                                 3
Chile-Argentina Border Region                                                                                                                                                                                                                                                    3
Irian Jaya Region, Indonesia                                                                                                                                                                                                                                                     3
Near N Coast Of New Guinea, Png.                                                                                                                                                                                                                                                 3
Andaman Islands, India Region                                                                                                                                                                                                                                                    3
Mindoro, Philippines                                                                                                                                                                                                                                                             3
South Of Mariana Islands                                                                                                                                                                                                                                                         3
Kamchatka Peninsula, Russia                                                                                                                                                                                                                                                      3
Virgin Islands, British                                                                                                                                                                                                                                                          3
North Of Franz Josef Land                                                                                                                                                                                                                                                        3
Dodecanese Islands, Greece                                                                                                                                                                                                                                                       3
Alaska Peninsula                                                                                                                                                                                                                                                                 3
South Shetland Islands                                                                                                                                                                                                                                                           3
North Korea                                                                                                                                                                                                                                                                      3
Nigeria                                                                                                                                                                                                                                                                          3
France                                                                                                                                                                                                                                                                           3
Tanzania                                                                                                                                                                                                                                                                         3
Poland                                                                                                                                                                                                                                                                           3
Thailand                                                                                                                                                                                                                                                                         3
Nepal                                                                                                                                                                                                                                                                            3
Nicaragua                                                                                                                                                                                                                                                                        3
Lebanon                                                                                                                                                                                                                                                                          3
Liberia                                                                                                                                                                                                                                                                          3
Zimbawe                                                                                                                                                                                                                                                                          3
United States of America                                                                                                                                                                                                                                                         3
Guinea-Bissau                                                                                                                                                                                                                                                                    3
Benin, Burkina Faso                                                                                                                                                                                                                                                              3
Burkina Faso, Benin                                                                                                                                                                                                                                                              3
Liberia, Guinea                                                                                                                                                                                                                                                                  3
Belize, Guatemala, Mexico                                                                                                                                                                                                                                                        2
Belize, Guatemala, Honduras, Mexico                                                                                                                                                                                                                                              2
Ireland, ,                                                                                                                                                                                                                                                                       2
Greece, Türkiye                                                                                                                                                                                                                                                                  2
India, Myanmar                                                                                                                                                                                                                                                                   2
Crete, Greece                                                                                                                                                                                                                                                                    2
North Of Severnaya Zemlya                                                                                                                                                                                                                                                        2
Niue                                                                                                                                                                                                                                                                             2
Miscellaneous (French) Indian Ocean Islands                                                                                                                                                                                                                                      2
Virgin Is.                                                                                                                                                                                                                                                                       2

In [468]:
master_disaster_dataset["country"] = (
    master_disaster_dataset["country"]
    .astype(str)
    .str.replace("\xa0", " ", regex=False)
    .str.strip()
)

print(master_disaster_dataset["country"].value_counts().head(20))

country
Indonesia             2520
Unknown               2213
Japan                 1423
United States         1244
Papua New Guinea       851
Chile                  846
Greece                 777
Philippines            656
China                  655
Russian Federation     623
Tonga                  623
Russia                 606
Australia              575
India                  545
Mexico                 527
Vanuatu                474
Türkiye                472
Peru                   399
Canada                 356
Fiji                   341
Name: count, dtype: int64

In [469]:
country_counts = master_disaster_dataset["country"].value_counts()

print("Total unique country values:", len(country_counts))

print("\nPotential naming variations:")
print(
    country_counts[
        country_counts.index.str.contains(
            "United States|America|Russia|Russian|Korea|Türkiye|Turkey|Congo|Burma|Myanmar|Venezuela|Zimbawe",
            case=False,
            na=False
        )
    ].to_string()
)

Total unique country values: 649

Potential naming variations:
country
United States                                                                                                                                                                                                              1244
Russian Federation                                                                                                                                                                                                          623
Russia                                                                                                                                                                                                                      606
Türkiye                                                                                                                                                                                                                     472
Myanmar                                                                                                                                                                                                                     208
The Democratic Republic of Congo                                                                                                                                                                                            188
Venezuela                                                                                                                                                                                                                    82
South Korea                                                                                                                                                                                                                  11
North Korea                                                                                                                                                                                                                  10
Off Coast Of Central America                                                                                                                                                                                                  8
Canada, United States                                                                                                                                                                                                         7
Congo, The Democratic Republic of the                                                                                                                                                                                         6
American Samoa                                                                                                                                                                                                                6
Myanmar, Thailand                                                                                                                                                                                                             6
Mexico, United States                                                                                                                                                                                                         5
Democratic Republic of the Congo                                                                                                                                                                                              5
Democratic Republic of Congo                                                                                                                                                                                                  5
Congo, DRC                                                                                                                                                                                                                    4
Kazakhstan, Russia                                                                                                                                                                                                            4
Angola, The Democratic Republic of Congo                                                                                                                                                                                      4
Colombia, Venezuela                                                                                                                                                                                                           3
Myanmar-India Border Region                                                                                                                                                                                                   3
Eastern Siberia, Russia                                                                                                                                                                                                       3
Kamchatka Peninsula, Russia                                                                                                                                                                                                   3
Zimbawe                                                                                                                                                                                                                       3
United States of America                                                                                                                                                                                                      3
Greece, Türkiye                                                                                                                                                                                                               2
India, Myanmar                                                                                                                                                                                                                2
Near Coast Of Venezuela                                                                                                                                                                                                       2
DR Congo                                                                                                                                                                                                                      2
Burma                                                                                                                                                                                                                         2
Congo                                                                                                                                                                                                                         2
Myanmar, Union of                                                                                                                                                                                                             2
Republic of Congo                                                                                                                                                                                                             2
Bangladesh, Myanmar                                                                                                                                                                                                           2
The Democratic Republic of Congo, Zambia                                                                                                                                                                                      2
Albania, Austria, Bosnia & Herzegovina, Bulgaria, Belarus, Greece, Croatia, Hungary, Kazakhstan, Moldova, Montenegro, Macedonia, Romania, Serbia, Russia, Slovenia, Slovakia, Türkiye, Ukraine                                1
China, India, Myanmar, Nepal                                                                                                                                                                                                  1
Bangladesh, India, Myanmar, Nepal                                                                                                                                                                                             1
Azerbaijan, Russia                                                                                                                                                                                                            1
Congo, DRC, Central African Republic, Kenya, South Sudan, Uganda                                                                                                                                                              1
Cambodia, Laos, Myanmar, Thailand, Vietnam                                                                                                                                                                                    1
Trinidad & Tobago, Venezuela                                                                                                                                                                                                  1
Belarus, Estonia, Lithuania, Latvia, Poland, Russia, Ukraine                                                                                                                                                                  1
China, North Korea, South Korea                                                                                                                                                                                               1
Bulgaria, Moldova, Romania, Türkiye, Ukraine                                                                                                                                                                                  1
Bhutan, China, India, Myanmar                                                                                                                                                                                                 1
Russia, Ukraine                                                                                                                                                                                                               1
Bulgaria, Iraq, Iran, Türkiye                                                                                                                                                                                                 1
Bangladesh, India, Myanmar                                                                                                                                                                                                    1
Burundi, Democratic Republic of Congo, Rwanda                                                                                                                                                                                 1
Kazakhstan, Russia, Uzbekistan                                                                                                                                                                                                1
Angola, Democratic Republic of Congo, Republic of Congo                                                                                                                                                                       1
Democratic Republic of Congo, Zambia                                                                                                                                                                                          1
China, Laos, Myanmar, Thailand                                                                                                                                                                                                1
Albania, Bulgaria, Greece, The Republic of North Macedonia, Türkiye                                                                                                                                                           1
Angola, Democratic Republic of Congo, Zambia                                                                                                                                                                                  1
Democratic Republic of Congo, Central African Republic, Republic of Congo, Cameroon, Gabon, Equatorial Guinea                                                                                                                 1
Moldova, Russia, Ukraine                                                                                                                                                                                                      1
Mongolia, Russia                                                                                                                                                                                                              1
Afghanistan, Israel, Iraq, Islamic Republic of Iran, Jordan, Kyrgyzstan, Kazakhstan, Lebanon, Pakistan, Gaza Strip, Syria, Tajikistan, Turkmenistan, Türkiye, Uzbekistan                                                      1
Republic of Korea                                                                                                                                                                                                             1
Primor'ye, Russia                                                                                                                                                                                                             1
Korea, Democratic People's Republic of                                                                                                                                                                                        1
Myanmar-China Border Region                                                                                                                                                                                                   1
Democratic Republic Of Congo                                                                                                                                                                                                  1
Southeastern Siberia, Russia                                                                                                                                                                                                  1
Greece,Türkiye                                                                                                                                                                                                                1
Northern Türkiye                                                                                                                                                                                                              1
Eastern Russia                                                                                                                                                                                                                1
Northwestern D R Congo                                                                                                                                                                                                        1
Congo Republic                                                                                                                                                                                                                1
Burma (Myanmar)                                                                                                                                                                                                               1
Burma/Myanmar                                                                                                                                                                                                                 1
Anguilla|Antigua and Barbuda|British Virgin Islands|Cuba|Dominican Republic|Puerto Rico|Saint Kitts and Nevis|Saint-Martin (French part)|Turks and Caicos Islands|United States of America|United States Virgin Islands       1
Russian Fed.                                                                                                                                                                                                                  1
Cuba|United States of America                                                                                                                                                                                                 1
Trinidad and Tobago, United States                                                                                                                                                                                            1
Congo-Brazzaville                                                                                                                                                                                                             1
Central African Republic, The Democratic Republic of Congo                                                                                                                                                                    1
The Democratic Republic of Congo, Central African Republic                                                                                                                                                                    1
Kazakhstan, Russian Federation                                                                                                                                                                                                1
Zambia, The Democratic Republic of Congo                                                                                                                                                                                      1
United States, Canada                                                                                                                                                                                                         1
The Democratic Republic of Congo, Sudan                                                                                                                                                                                       1
Sudan, The Democratic Republic of Congo                                                                                                                                                                                       1
Russian Federation, China                                                                                                                                                                                                     1
The Democratic Republic of Congo, Angola                                                                                                                                                                                      1

In [470]:
country_keywords = [
    "Border",
    "Region",
    "Sea",
    "Ocean",
    "Coast",
    "Peninsula",
    "Islands",
    "Island",
    "Ridge",
    "Off ",
    "Near ",
    "North Of",
    "South Of",
    "East Of",
    "West Of"
]

pattern = "|".join(country_keywords)

non_country_like = master_disaster_dataset[
    master_disaster_dataset["country"].str.contains(
        pattern,
        case=False,
        na=False
    )
]

print("Records with geographic/region-like country values:")
print(len(non_country_like))

print("\nExamples:")
print(
    non_country_like["country"]
    .value_counts()
    .head(30)
)

Records with geographic/region-like country values:
1672

Examples:
country
Solomon Islands                                 171
South Georgia and the South Sandwich Islands    141
Northern Mariana Islands                        119
South Of Fiji Islands                            91
Kermadec Islands Region                          65
Northern Mid-Atlantic Ridge                      56
Fiji Islands Region                              55
Reykjanes Ridge                                  51
Kermadec Islands, New Zealand                    44
Central Mid-Atlantic Ridge                       42
South Of Kermadec Islands                        41
Bonin Islands, Japan Region                      34
South Georgia / South Sandwich Islands           33
Carlsberg Ridge                                  30
Southern Mid-Atlantic Ridge                      28
Mariana Islands Region                           28
Mid-Indian Ridge                                 26
Volcano Islands, Japan Region                    23
Southeast Of Honshu, Japan                       22
Pacific-Antarctic Ridge                          22
Tonga Islands                                    20
Vanuatu Islands                                  17
Western Indian-Antarctic Ridge                   16
British Indian Ocean Territory                   15
South Sandwich Islands Region                    15
Southeast Indian Ridge                           14
Fox Islands, Aleutian Islands                    14
West Of Macquarie Island                         13
Mariana Islands                                  13
Southwest Indian Ridge                           12
Name: count, dtype: int64

In [471]:
master_disaster_dataset["country_clean"] = (
    master_disaster_dataset["country"]
    .replace({
        "United States of America": "United States",
        "Russian Federation": "Russia",
        "Russian Fed.": "Russia",
        "Zimbawe": "Zimbabwe",
        "Republic of Korea": "South Korea",
        "Korea, Democratic People's Republic of": "North Korea",
        "Democratic Republic of the Congo": "Democratic Republic of the Congo",
        "Democratic Republic Of Congo": "Democratic Republic of the Congo",
        "Democratic Republic of Congo": "Democratic Republic of the Congo",
        "DR Congo": "Democratic Republic of the Congo",
        "Congo, DRC": "Democratic Republic of the Congo",
        "Congo Republic": "Republic of the Congo",
        "Burma": "Myanmar",
        "Burma (Myanmar)": "Myanmar",
        "Burma/Myanmar": "Myanmar",
        "Myanmar, Union of": "Myanmar"
    })
)

print(master_disaster_dataset[
    ["country", "country_clean"]
].drop_duplicates().head(30))

                                              country  \
0    Germany, Denmark, France, Latvia, Poland, Sweden
1                                          Uzbekistan
2                                              Brazil
3                                           Australia
4                                          Madagascar
5   Albania, Austria, Bosnia & Herzegovina, Bulgar...
6                                        South Africa
7                                           Indonesia
9                                       United States
10         The Gambia, Guinea, Guinea-Bissau, Senegal
13                       China, India, Myanmar, Nepal
14                  Bangladesh, India, Myanmar, Nepal
15                                             Russia
16                                         Congo, DRC
17                                        Philippines
18                                    India, Pakistan
20                                              China
21                                             Mexico
22                        Cameroon, Equatorial Guinea
23                                  Guatemala, Mexico
24                          Belize, Guatemala, Mexico
25                  Cambodia, Laos, Thailand, Vietnam
26                     Central African Republic, Chad
27                Belize, Guatemala, Honduras, Mexico
28                                            Ecuador
29     Kyrgyzstan, Kazakhstan, Tajikistan, Uzbekistan
30                                              Chile
31                  Afghanistan, Pakistan, Tajikistan
32            Afghanistan, Iran, Pakistan, Tajikistan
33     Belize, Guatemala, Honduras, Mexico, Nicaragua

                                        country_clean
0    Germany, Denmark, France, Latvia, Poland, Sweden
1                                          Uzbekistan
2                                              Brazil
3                                           Australia
4                                          Madagascar
5   Albania, Austria, Bosnia & Herzegovina, Bulgar...
6                                        South Africa
7                                           Indonesia
9                                       United States
10         The Gambia, Guinea, Guinea-Bissau, Senegal
13                       China, India, Myanmar, Nepal
14                  Bangladesh, India, Myanmar, Nepal
15                                             Russia
16                   Democratic Republic of the Congo
17                                        Philippines
18                                    India, Pakistan
20                                              China
21                                             Mexico
22                        Cameroon, Equatorial Guinea
23                                  Guatemala, Mexico
24                          Belize, Guatemala, Mexico
25                  Cambodia, Laos, Thailand, Vietnam
26                     Central African Republic, Chad
27                Belize, Guatemala, Honduras, Mexico
28                                            Ecuador
29     Kyrgyzstan, Kazakhstan, Tajikistan, Uzbekistan
30                                              Chile
31                  Afghanistan, Pakistan, Tajikistan
32            Afghanistan, Iran, Pakistan, Tajikistan
33     Belize, Guatemala, Honduras, Mexico, Nicaragua

In [472]:
possible_variants = [
    "Venezulea",
    "Guatamala",
    "Camaroun",
    "Phillipines",
    "Columbia",
    "Russa",
    "Zimbawe",
    "Türkiye",
    "The Gambia",
    "Cote d'Ivoire"
]

for value in possible_variants:
    matches = master_disaster_dataset[
        master_disaster_dataset["country"].str.contains(
            value,
            case=False,
            na=False
        )
    ]

    if len(matches) > 0:
        print(f"{value}: {len(matches)} records")

Venezulea: 1 records
Guatamala: 1 records
Camaroun: 1 records
Phillipines: 4 records
Columbia: 15 records
Russa: 1 records
Zimbawe: 3 records
Türkiye: 481 records
The Gambia: 1 records
Cote d'Ivoire: 9 records

In [473]:
master_disaster_dataset["country_clean"] = (
    master_disaster_dataset["country_clean"]
    .replace({
        "Venezulea": "Venezuela",
        "Guatamala": "Guatemala",
        "Camaroun": "Cameroon",
        "Phillipines": "Philippines",
        "Columbia": "Colombia",
        "Russa": "Russia",
        "Zimbawe": "Zimbabwe"
    })
)

print(
    master_disaster_dataset[
        master_disaster_dataset["country"].isin([
            "Venezulea",
            "Guatamala",
            "Camaroun",
            "Phillipines",
            "Columbia",
            "Russa",
            "Zimbawe"
        ])
    ][["country", "country_clean"]]
)

           country country_clean
20647     Columbia      Colombia
20736     Columbia      Colombia
20804  Phillipines   Philippines
20859     Columbia      Colombia
20878  Phillipines   Philippines
20905  Phillipines   Philippines
20916     Columbia      Colombia
20979     Columbia      Colombia
21020     Columbia      Colombia
21067     Columbia      Colombia
21158     Columbia      Colombia
21247     Columbia      Colombia
21260     Columbia      Colombia
21378    Venezulea     Venezuela
21494  Phillipines   Philippines
21663     Columbia      Colombia
21679    Guatamala     Guatemala
21777     Columbia      Colombia
21819     Columbia      Colombia
21845     Columbia      Colombia
21923     Columbia      Colombia
21943      Zimbawe      Zimbabwe
21944      Zimbawe      Zimbabwe
21947      Zimbawe      Zimbabwe
21969        Russa        Russia
22026     Camaroun      Cameroon

In [474]:
check_values = [
    "Venezulea",
    "Guatamala",
    "Camaroun",
    "Phillipines",
    "Columbia",
    "Russa",
    "Zimbawe"
]

print(
    master_disaster_dataset[
        master_disaster_dataset["country_clean"].isin(check_values)
    ]["country_clean"].value_counts()
)

Series([], Name: count, dtype: int64)

In [475]:
print("Unique country_clean values:", master_disaster_dataset["country_clean"].nunique())

print("\nTop 30 values:")
print(
    master_disaster_dataset["country_clean"]
    .value_counts()
    .head(30)
)

Unique country_clean values: 629

Top 30 values:
country_clean
Indonesia                           2520
Unknown                             2213
Japan                               1423
United States                       1247
Russia                              1231
Papua New Guinea                     851
Chile                                846
Greece                               777
Philippines                          660
China                                655
Tonga                                623
Australia                            575
India                                545
Mexico                               527
Vanuatu                              474
Türkiye                              472
Peru                                 399
Canada                               356
Fiji                                 341
Argentina                            280
Brazil                               246
Myanmar                              214
New Zealand                          208
Colombia                             191
The Democratic Republic of Congo     188
Iran                                 181
Angola                               178
Solomon Islands                      171
Sudan                                169
Guatemala                            166
Name: count, dtype: int64

In [476]:
multi_location = master_disaster_dataset["country_clean"].str.contains(
    r",|\||-.*Border|Region|Coast|Sea|Ocean|Ridge|Peninsula",
    case=False,
    na=False
)

print("Multi-location / geographic records:", multi_location.sum())
print(
    "Percentage:",
    round(multi_location.mean() * 100, 2),
    "%"
)

Multi-location / geographic records: 1313
Percentage: 5.02 %

In [477]:
master_disaster_dataset["location_type"] = np.where(
    multi_location,
    "Multi/Geographic",
    "Single"
)

print(master_disaster_dataset["location_type"].value_counts())

location_type
Single              24857
Multi/Geographic     1313
Name: count, dtype: int64

In [478]:
print("Dataset shape:", master_disaster_dataset.shape)

print("\nColumns:")
print(master_disaster_dataset.columns.tolist())

print("\nData types:")
print(master_disaster_dataset.dtypes)

Dataset shape: (26170, 16)

Columns:
['description', 'alertlevel', 'alertscore', 'episodealertscore', 'country', 'fromdate', 'todate', 'iso3', 'longitude', 'latitude', 'disaster_type', 'year', 'month', 'duration_days', 'country_clean', 'location_type']

Data types:
description                     str
alertlevel                      str
alertscore                  float64
episodealertscore           float64
country                         str
fromdate             datetime64[us]
todate               datetime64[us]
iso3                            str
longitude                   float64
latitude                    float64
disaster_type                   str
year                          int32
month                         int32
duration_days               float64
country_clean                   str
location_type                   str
dtype: object

In [479]:
print("Dataset shape:", master_disaster_dataset.shape)

print("\nColumns:")
print(master_disaster_dataset.columns.tolist())

print("\nData types:")
print(master_disaster_dataset.dtypes)

print(master_disaster_dataset.dtypes)
print("Dataset shape:", master_disaster_dataset.shape)

print("\nColumns:")
print(master_disaster_dataset.columns.tolist())

print("\nData types:")
print(master_disaster_dataset.dtypes)
print("Dataset shape:", master_disaster_dataset.shape)

print("\nColumns:")
print(master_disaster_dataset.columns.tolist())

print("\nData types:")
print(master_disaster_dataset.dtypes.to_string())

Dataset shape: (26170, 16)

Columns:
['description', 'alertlevel', 'alertscore', 'episodealertscore', 'country', 'fromdate', 'todate', 'iso3', 'longitude', 'latitude', 'disaster_type', 'year', 'month', 'duration_days', 'country_clean', 'location_type']

Data types:
description                     str
alertlevel                      str
alertscore                  float64
episodealertscore           float64
country                         str
fromdate             datetime64[us]
todate               datetime64[us]
iso3                            str
longitude                   float64
latitude                    float64
disaster_type                   str
year                          int32
month                         int32
duration_days               float64
country_clean                   str
location_type                   str
dtype: object
description                     str
alertlevel                      str
alertscore                  float64
episodealertscore           float64
country                         str
fromdate             datetime64[us]
todate               datetime64[us]
iso3                            str
longitude                   float64
latitude                    float64
disaster_type                   str
year                          int32
month                         int32
duration_days               float64
country_clean                   str
location_type                   str
dtype: object
Dataset shape: (26170, 16)

Columns:
['description', 'alertlevel', 'alertscore', 'episodealertscore', 'country', 'fromdate', 'todate', 'iso3', 'longitude', 'latitude', 'disaster_type', 'year', 'month', 'duration_days', 'country_clean', 'location_type']

Data types:
description                     str
alertlevel                      str
alertscore                  float64
episodealertscore           float64
country                         str
fromdate             datetime64[us]
todate               datetime64[us]
iso3                            str
longitude                   float64
latitude                    float64
disaster_type                   str
year                          int32
month                         int32
duration_days               float64
country_clean                   str
location_type                   str
dtype: object
Dataset shape: (26170, 16)

Columns:
['description', 'alertlevel', 'alertscore', 'episodealertscore', 'country', 'fromdate', 'todate', 'iso3', 'longitude', 'latitude', 'disaster_type', 'year', 'month', 'duration_days', 'country_clean', 'location_type']

Data types:
description                     str
alertlevel                      str
alertscore                  float64
episodealertscore           float64
country                         str
fromdate             datetime64[us]
todate               datetime64[us]
iso3                            str
longitude                   float64
latitude                    float64
disaster_type                   str
year                          int32
month                         int32
duration_days               float64
country_clean                   str
location_type                   str

In [480]:
print(
    master_disaster_dataset[
        [
            "alertscore",
            "episodealertscore",
            "longitude",
            "latitude",
            "year",
            "month",
            "duration_days"
        ]
    ].describe()
)

         alertscore  episodealertscore     longitude      latitude  \
count  26170.000000       25556.000000  26170.000000  26170.000000
mean       1.031410           0.408786     31.278918     10.647664
std        0.202225           0.395228    109.972878     28.817193
min        1.000000          -0.993950   -179.990000    -66.860000
25%        1.000000           0.000000    -70.591425    -11.202310
50%        1.000000           0.500000     52.683900      9.738450
75%        1.000000           0.500000    128.462375     36.288025
max        3.000000           3.786233    180.000000     86.893200

               year         month  duration_days
count  26170.000000  26170.000000   26170.000000
mean    2012.890218      6.498777       4.688696
std        6.652554      3.453255      28.491569
min     2000.000000      1.000000       0.000000
25%     2007.000000      3.000000       0.000000
50%     2013.000000      6.000000       0.000000
75%     2018.000000     10.000000       0.000000
max     2025.000000     12.000000    1056.000000

In [481]:
negative_episode_score = master_disaster_dataset[
    master_disaster_dataset["episodealertscore"] < 0
]

print("Negative episodealertscore records:", len(negative_episode_score))

print("\nValues:")
print(
    negative_episode_score["episodealertscore"]
    .value_counts()
    .sort_index()
    .head(30)
)

Negative episodealertscore records: 302

Values:
episodealertscore
-0.993950    1
-0.987919    1
-0.987801    1
-0.985143    1
-0.983350    1
-0.982772    1
-0.979897    1
-0.978587    1
-0.978558    1
-0.977050    1
-0.976644    1
-0.975565    1
-0.974779    1
-0.974683    1
-0.974466    1
-0.974225    1
-0.973133    1
-0.971535    1
-0.970824    1
-0.970501    1
-0.970456    1
-0.970220    1
-0.969327    1
-0.968679    1
-0.968398    1
-0.968313    1
-0.967827    1
-0.966976    1
-0.966057    1
-0.964784    1
Name: count, dtype: int64

In [482]:
master_disaster_dataset.loc[
    master_disaster_dataset["episodealertscore"] < 0,
    "episodealertscore"
] = np.nan

print(
    "Missing episodealertscore:",
    master_disaster_dataset["episodealertscore"].isna().sum()
)

Missing episodealertscore: 916

In [483]:
print(
    master_disaster_dataset["episodealertscore"]
    .describe()
)

print("\nHighest episodealertscore values:")
print(
    master_disaster_dataset["episodealertscore"]
    .nlargest(20)
    .to_string(index=False)
)

count    25254.000000
mean         0.423020
std          0.374724
min          0.000000
25%          0.000000
50%          0.500000
75%          0.500000
max          3.786233
Name: episodealertscore, dtype: float64

Highest episodealertscore values:
3.786233
3.729296
3.425000
3.402768
3.221419
3.163879
3.000000
3.000000
3.000000
3.000000
3.000000
3.000000
3.000000
3.000000
3.000000
3.000000
3.000000
3.000000
3.000000
3.000000

In [484]:
high_episode_scores = master_disaster_dataset[
    master_disaster_dataset["episodealertscore"] > 3
]

print("Records with episodealertscore > 3:", len(high_episode_scores))

print("\nBy disaster type:")
print(
    high_episode_scores["disaster_type"]
    .value_counts()
)

print("\nHighest values with disaster type:")
print(
    high_episode_scores[
        ["disaster_type", "episodealertscore", "country"]
    ]
    .sort_values("episodealertscore", ascending=False)
    .head(20)
    .to_string(index=False)
)

Records with episodealertscore > 3: 6

By disaster type:
disaster_type
Earthquake    6
Name: count, dtype: int64

Highest values with disaster type:
disaster_type  episodealertscore          country
   Earthquake           3.786233      Afghanistan
   Earthquake           3.729296    United States
   Earthquake           3.425000 Papua New Guinea
   Earthquake           3.402768            India
   Earthquake           3.221419        Indonesia
   Earthquake           3.163879            Nepal

In [485]:
print("Invalid longitude:",
      ((master_disaster_dataset["longitude"] < -180) |
       (master_disaster_dataset["longitude"] > 180)).sum())

print("Invalid latitude:",
      ((master_disaster_dataset["latitude"] < -90) |
       (master_disaster_dataset["latitude"] > 90)).sum())

Invalid longitude: 0
Invalid latitude: 0

In [486]:
print("Invalid year:",
      ((master_disaster_dataset["year"] < 2000) |
       (master_disaster_dataset["year"] > 2025)).sum())

print("Invalid month:",
      ((master_disaster_dataset["month"] < 1) |
       (master_disaster_dataset["month"] > 12)).sum())

Invalid year: 0
Invalid month: 0

In [487]:
print(
    "Negative durations:",
    (master_disaster_dataset["duration_days"] < 0).sum()
)

print(
    "Durations greater than 365 days:",
    (master_disaster_dataset["duration_days"] > 365).sum()
)

Negative durations: 0
Durations greater than 365 days: 43

In [488]:
missing_values = master_disaster_dataset.isnull().sum()

print(missing_values[missing_values > 0])

episodealertscore    916
dtype: int64

In [489]:
master_disaster_dataset.to_csv(
    "master_disaster_dataset_cleaned.csv",
    index=False
)

print("Cleaned master dataset saved successfully.")
print("Shape:", master_disaster_dataset.shape)

Cleaned master dataset saved successfully.
Shape: (26170, 16)

In [490]:
for i, column in enumerate(master_disaster_dataset.columns, start=1):
    print(i, "→", column)

1 → description
2 → alertlevel
3 → alertscore
4 → episodealertscore
5 → country
6 → fromdate
7 → todate
8 → iso3
9 → longitude
10 → latitude
11 → disaster_type
12 → year
13 → month
14 → duration_days
15 → country_clean
16 → location_type

In [491]:
feature_roles = pd.DataFrame({
    "column": master_disaster_dataset.columns,
    "dtype": master_disaster_dataset.dtypes.astype(str).values
})

print(feature_roles.to_string(index=False))

           column          dtype
      description            str
       alertlevel            str
       alertscore        float64
episodealertscore        float64
          country            str
         fromdate datetime64[us]
           todate datetime64[us]
             iso3            str
        longitude        float64
         latitude        float64
    disaster_type            str
             year          int32
            month          int32
    duration_days        float64
    country_clean            str
    location_type            str

In [492]:
print(
    master_disaster_dataset["disaster_type"]
    .value_counts()
)

disaster_type
Earthquake          20290
Forest Fire          3048
Flood                2126
Tropical Cyclone      405
Drought               240
Eruption               61
Name: count, dtype: int64

In [493]:
print(
    master_disaster_dataset[
        ["description", "disaster_type"]
    ].head(20).to_string(index=False)
)

                                                                                                                                                                                                                                             description disaster_type
                                                                                                                                                  Green Drought in Germany, Denmark, France, Latvia, Poland, Sweden from: 21 Jul 2017  to: 09 Feb 2019 .       Drought
                                                                                                                                                                                        Green Drought in Uzbekistan from: 21 Nov 2017  to: 06 Sep 2018 .       Drought
                                                                                                                                                                                            Green Drought in Brazil from: 21 Dec 2017  to: 06 Sep 2018 .       Drought
                                                                                                                                                                                        Orange Drought in Australia from: 21 Feb 2018  to: 24 Nov 2018 .       Drought
                                                                                                                                                                                       Orange Drought in Madagascar from: 21 Mar 2018  to: 13 Sep 2018 .       Drought
Green Drought in Albania, Austria, Bosnia  and  Herzegovina, Bulgaria, Belarus, Greece, Croatia, Hungary, Kazakhstan, Moldova, Montenegro, Macedonia, Romania, Serbia, Russia, Slovenia, Slovakia, Türkiye, Ukraine from: 21 Apr 2018  to: 24 Nov 2018 .       Drought
                                                                                                                                                                                      Green Drought in South Africa from: 21 Apr 2018  to: 10 Oct 2018 .       Drought
                                                                                                                                                                                         Green Drought in Indonesia from: 21 Apr 2018  to: 29 Aug 2018 .       Drought
                                                                                                                                                                                            Green Drought in Brazil from: 21 May 2018  to: 30 Dec 2018 .       Drought
                                                                                                                                                                                     Green Drought in United States from: 21 May 2018  to: 28 Oct 2018 .       Drought
                                                                                                                                                        Green Drought in The Gambia, Guinea, Guinea-Bissau, Senegal from: 21 May 2018  to: 10 Oct 2018 .       Drought
                                                                                                                                                                                            Green Drought in Brazil from: 11 May 2018  to: 10 Oct 2018 .       Drought
                                                                                                                                                                                     Green Drought in United States from: 21 May 2018  to: 20 Aug 2018 .       Drought
                                                                                                                                                                     Orange Drought in China, India, Myanmar, Nepal from: 21 Jun 2018  to: 16 Feb 2019 .       Drought
                                                                                                                                                                 Green Drought in Bangladesh, India, Myanmar, Nepal from: 21 Jun 2018  to: 16 Nov 2018 .       Drought
                                                                                                                                                                                            Green Drought in Russia from: 21 Jun 2018  to: 10 Oct 2018 .       Drought
                                                                                                                                                                                        Green Drought in Congo, DRC from: 21 Jun 2018  to: 10 Oct 2018 .       Drought
                                                                                                                                                                                       Green Drought in Philippines from: 21 Jul 2018  to: 26 Jan 2019 .       Drought
                                                                                                                                                                                  Orange Drought in India, Pakistan from: 21 Jul 2018  to: 30 Dec 2018 .       Drought
                                                                                                                                                                                        Green Drought in Madagascar from: 21 Jul 2018  to: 24 Nov 2018 .       Drought

In [494]:
alert_disaster_table = pd.crosstab(
    master_disaster_dataset["alertlevel"],
    master_disaster_dataset["disaster_type"]
)

print(alert_disaster_table)

disaster_type  Drought  Earthquake  Eruption  Flood  Forest Fire  \
alertlevel
Green              198       20056        46   1826         3047
Orange              36         193        12    249            1
Red                  6          41         3     51            0

disaster_type  Tropical Cyclone
alertlevel
Green                       312
Orange                       57
Red                          36

In [495]:
print("Unique ISO3 values:", master_disaster_dataset["iso3"].nunique())

print("\nTop 20 ISO3 values:")
print(
    master_disaster_dataset["iso3"]
    .value_counts()
    .head(20)
)

Unique ISO3 values: 242

Top 20 ISO3 values:
iso3
IDN        2529
           2217
JPN        1456
USA        1393
RUS        1248
Unknown    1081
PNG         874
CHL         867
GRC         781
PHL         684
CHN         662
TON         632
AUS         578
MEX         561
IND         527
VUT         490
TUR         468
PER         406
CAN         354
FJI         350
Name: count, dtype: int64

In [496]:
blank_iso3 = master_disaster_dataset[
    master_disaster_dataset["iso3"].isin(["", "Unknown"])
]

print("Blank/Unknown ISO3 rows:", len(blank_iso3))

print("\nDisaster type distribution:")
print(blank_iso3["disaster_type"].value_counts())

print("\nLocation type distribution:")
print(blank_iso3["location_type"].value_counts())

Blank/Unknown ISO3 rows: 1081

Disaster type distribution:
disaster_type
Earthquake    1081
Name: count, dtype: int64

Location type distribution:
location_type
Single              589
Multi/Geographic    492
Name: count, dtype: int64

In [497]:
numerical_features = [
    "alertscore",
    "episodealertscore",
    "longitude",
    "latitude",
    "year",
    "month",
    "duration_days"
]

print(
    master_disaster_dataset.groupby("disaster_type")[numerical_features]
    .mean()
    .round(2)
)

                  alertscore  episodealertscore  longitude  latitude     year  \
disaster_type
Drought                 1.20               0.62      10.66     14.49  2020.71
Earthquake              1.01               0.32      31.44     10.05  2011.50
Eruption                1.30               0.76      39.13      9.10  2018.70
Flood                   1.17               1.01      30.69     16.20  2010.23
Forest Fire             1.00               0.55      33.58      9.94  2022.77
Tropical Cyclone        1.32               1.07      19.91     14.68  2016.54

                  month  duration_days
disaster_type
Drought            6.39         219.72
Earthquake         6.50           0.00
Eruption           6.79          78.82
Flood              6.45          13.05
Forest Fire        6.43          11.48
Tropical Cyclone   7.20           6.01

In [498]:
candidate_features = [
    "alertscore",
    "episodealertscore",
    "longitude",
    "latitude",
    "year",
    "month",
    "duration_days",
    "location_type"
]

print(
    master_disaster_dataset[candidate_features]
    .isnull()
    .sum()
)

alertscore             0
episodealertscore    916
longitude              0
latitude               0
year                   0
month                  0
duration_days          0
location_type          0
dtype: int64

In [499]:
datasets = {
    "Drought": drought,
    "Earthquake": earthquake,
    "Eruption": eruption,
    "Flood": flood,
    "Forest Fire": forest_fires,
    "Tropical Cyclone": tropical_cyclone
}

for name, df in datasets.items():
    print(f"\n{'=' * 60}")
    print(f"{name}")
    print(f"Shape: {df.shape}")
    print("Columns:")
    print(list(df.columns))

============================================================
Drought
Shape: (240, 13)
Columns:
['description', 'alertlevel', 'alertscore', 'episodealertlevel', 'episodealertscore', 'country', 'fromdate', 'todate', 'iso3', 'gdacs_id', 'longitude', 'latitude', 'disaster_type']

============================================================
Earthquake
Shape: (20290, 13)
Columns:
['description', 'alertlevel', 'alertscore', 'episodealertlevel', 'episodealertscore', 'country', 'fromdate', 'todate', 'iso3', 'gdacs_id', 'longitude', 'latitude', 'disaster_type']

============================================================
Eruption
Shape: (61, 13)
Columns:
['description', 'alertlevel', 'alertscore', 'episodealertlevel', 'episodealertscore', 'country', 'fromdate', 'todate', 'iso3', 'gdacs_id', 'longitude', 'latitude', 'disaster_type']

============================================================
Flood
Shape: (2126, 13)
Columns:
['description', 'alertlevel', 'alertscore', 'episodealertlevel', 'episodealertscore', 'country', 'fromdate', 'todate', 'iso3', 'gdacs_id', 'longitude', 'latitude', 'disaster_type']

============================================================
Forest Fire
Shape: (3051, 13)
Columns:
['description', 'alertlevel', 'alertscore', 'episodealertlevel', 'episodealertscore', 'country', 'fromdate', 'todate', 'iso3', 'gdacs_id', 'longitude', 'latitude', 'disaster_type']

============================================================
Tropical Cyclone
Shape: (405, 13)
Columns:
['description', 'alertlevel', 'alertscore', 'episodealertlevel', 'episodealertscore', 'country', 'fromdate', 'todate', 'iso3', 'gdacs_id', 'longitude', 'latitude', 'disaster_type']

In [500]:
drought_raw = pd.read_csv("Drought_clean.csv")
earthquake_raw = pd.read_csv("Earthquake_clean.csv")
eruption_raw = pd.read_csv("Eruption_clean.csv")
flood_raw = pd.read_csv("Flood_clean.csv")
forest_fires_raw = pd.read_csv("Forest_Fires_clean.csv")
tropical_cyclone_raw = pd.read_csv("Tropical_Cyclone_clean.csv")

raw_datasets = {
    "Drought": drought_raw,
    "Earthquake": earthquake_raw,
    "Eruption": eruption_raw,
    "Flood": flood_raw,
    "Forest Fire": forest_fires_raw,
    "Tropical Cyclone": tropical_cyclone_raw
}

for name, df in raw_datasets.items():
    print(f"{name}: {df.shape}")

Drought: (240, 14)
Earthquake: (20290, 16)
Eruption: (61, 18)
Flood: (2126, 17)
Forest Fire: (3051, 14)
Tropical Cyclone: (405, 20)

In [501]:
for name, df in raw_datasets.items():
    print(f"\n{'=' * 70}")
    print(name)
    print(list(df.columns))

======================================================================
Drought
['Description', 'Alertlevel', 'Alertscore', 'Episodealertscore', 'Country', 'Fromdate', 'Todate', 'Severity (km2)', 'Iso3', 'Gdacs id', 'Duration (days)', 'Impact', 'Longitude', 'Latitude']

======================================================================
Earthquake
['description', 'alertlevel', 'alertscore', 'episodealertlevel', 'episodealertscore', 'country', 'fromdate', 'todate', 'source', 'iso3', 'Earthquake Magnitude (M)', 'Capacity', 'Depth (km)', 'longitude', 'latitude', 'Exposed Population (within 100 km)']

======================================================================
Eruption
['description', 'alertlevel', 'alertscore', 'episodealertlevel', 'episodealertscore', 'country', 'fromdate', 'todate', 'severity', 'source', 'iso3', 'GDACS ID', 'Exposed Population 30km', 'Exposed Population 100km', 'Max Volc. Explosivity Index VEI', 'Population Exposure Index PEI', 'longitude', 'latitude']

======================================================================
Flood
['Unnamed: 0', 'description', 'alertlevel', 'alertscore', 'episodealertlevel', 'episodealertscore', 'country', 'fromdate', 'todate', 'severity (magnitude)', 'source', 'iso3', 'Death', 'Displaced', 'GDACS_ID', 'longitude', 'latitude']

======================================================================
Forest Fire
['description', 'alertlevel', 'alertscore', 'episodealertscore', 'country', 'fromdate', 'todate', 'severity (ha)', 'iso3', 'GDACS ID', 'People affected', 'Duration (days)', 'longitude', 'latitude']

======================================================================
Tropical Cyclone
['description', 'alertlevel', 'alertscore', 'episodealertlevel', 'episodealertscore', 'fromdate', 'todate', 'severity', 'severitytext', 'source', 'iso3', 'GDACS ID', 'Exposed countries', 'Exposed population', 'Maximum wind speed (km/h)', 'Maximum storm surge (m)', 'Vulnerability', 'longitude', 'latitude', 'Category']

In [502]:
# Make copies so the original raw datasets remain unchanged
drought_ml = drought_raw.copy()
earthquake_ml = earthquake_raw.copy()
eruption_ml = eruption_raw.copy()
flood_ml = flood_raw.copy()
forest_fires_ml = forest_fires_raw.copy()
tropical_cyclone_ml = tropical_cyclone_raw.copy()


# Standardize column names
def standardize_ml_columns(df):
    df = df.copy()

    df.columns = (
        df.columns
        .str.strip()
        .str.lower()
        .str.replace(" ", "_")
        .str.replace("(", "", regex=False)
        .str.replace(")", "", regex=False)
    )

    return df


drought_ml = standardize_ml_columns(drought_ml)
earthquake_ml = standardize_ml_columns(earthquake_ml)
eruption_ml = standardize_ml_columns(eruption_ml)
flood_ml = standardize_ml_columns(flood_ml)
forest_fires_ml = standardize_ml_columns(forest_fires_ml)
tropical_cyclone_ml = standardize_ml_columns(tropical_cyclone_ml)


# Add disaster type
drought_ml["disaster_type"] = "Drought"
earthquake_ml["disaster_type"] = "Earthquake"
eruption_ml["disaster_type"] = "Eruption"
flood_ml["disaster_type"] = "Flood"
forest_fires_ml["disaster_type"] = "Forest Fire"
tropical_cyclone_ml["disaster_type"] = "Tropical Cyclone"


print("Column standardization completed.")

Column standardization completed.

In [503]:
ml_datasets = {
    "Drought": drought_ml,
    "Earthquake": earthquake_ml,
    "Eruption": eruption_ml,
    "Flood": flood_ml,
    "Forest Fire": forest_fires_ml,
    "Tropical Cyclone": tropical_cyclone_ml
}

for name, df in ml_datasets.items():
    print(f"\n{'=' * 70}")
    print(name)
    print("Shape:", df.shape)
    print("Columns:")
    print(list(df.columns))

======================================================================
Drought
Shape: (240, 15)
Columns:
['description', 'alertlevel', 'alertscore', 'episodealertscore', 'country', 'fromdate', 'todate', 'severity_km2', 'iso3', 'gdacs_id', 'duration_days', 'impact', 'longitude', 'latitude', 'disaster_type']

======================================================================
Earthquake
Shape: (20290, 17)
Columns:
['description', 'alertlevel', 'alertscore', 'episodealertlevel', 'episodealertscore', 'country', 'fromdate', 'todate', 'source', 'iso3', 'earthquake_magnitude_m', 'capacity', 'depth_km', 'longitude', 'latitude', 'exposed_population_within_100_km', 'disaster_type']

======================================================================
Eruption
Shape: (61, 19)
Columns:
['description', 'alertlevel', 'alertscore', 'episodealertlevel', 'episodealertscore', 'country', 'fromdate', 'todate', 'severity', 'source', 'iso3', 'gdacs_id', 'exposed_population_30km', 'exposed_population_100km', 'max_volc._explosivity_index_vei', 'population_exposure_index_pei', 'longitude', 'latitude', 'disaster_type']

======================================================================
Flood
Shape: (2126, 18)
Columns:
['unnamed:_0', 'description', 'alertlevel', 'alertscore', 'episodealertlevel', 'episodealertscore', 'country', 'fromdate', 'todate', 'severity_magnitude', 'source', 'iso3', 'death', 'displaced', 'gdacs_id', 'longitude', 'latitude', 'disaster_type']

======================================================================
Forest Fire
Shape: (3051, 15)
Columns:
['description', 'alertlevel', 'alertscore', 'episodealertscore', 'country', 'fromdate', 'todate', 'severity_ha', 'iso3', 'gdacs_id', 'people_affected', 'duration_days', 'longitude', 'latitude', 'disaster_type']

======================================================================
Tropical Cyclone
Shape: (405, 21)
Columns:
['description', 'alertlevel', 'alertscore', 'episodealertlevel', 'episodealertscore', 'fromdate', 'todate', 'severity', 'severitytext', 'source', 'iso3', 'gdacs_id', 'exposed_countries', 'exposed_population', 'maximum_wind_speed_km/h', 'maximum_storm_surge_m', 'vulnerability', 'longitude', 'latitude', 'category', 'disaster_type']

In [504]:
# Remove the unnecessary Flood index column
if "unnamed:_0" in flood_ml.columns:
    flood_ml = flood_ml.drop(columns=["unnamed:_0"])


# Rename awkward feature names
eruption_ml = eruption_ml.rename(columns={
    "max_volc._explosivity_index_vei": "vei"
})

tropical_cyclone_ml = tropical_cyclone_ml.rename(columns={
    "maximum_wind_speed_km/h": "maximum_wind_speed_kmh"
})


# Check the important disaster-specific features
print("Drought:", [c for c in drought_ml.columns if c not in master_columns])
print("Earthquake:", [c for c in earthquake_ml.columns if c not in master_columns])
print("Eruption:", [c for c in eruption_ml.columns if c not in master_columns])
print("Flood:", [c for c in flood_ml.columns if c not in master_columns])
print("Forest Fire:", [c for c in forest_fires_ml.columns if c not in master_columns])
print("Tropical Cyclone:", [c for c in tropical_cyclone_ml.columns if c not in master_columns])

Drought: ['severity_km2', 'duration_days', 'impact']
Earthquake: ['source', 'earthquake_magnitude_m', 'capacity', 'depth_km', 'exposed_population_within_100_km']
Eruption: ['severity', 'source', 'exposed_population_30km', 'exposed_population_100km', 'vei', 'population_exposure_index_pei']
Flood: ['severity_magnitude', 'source', 'death', 'displaced']
Forest Fire: ['severity_ha', 'people_affected', 'duration_days']
Tropical Cyclone: ['severity', 'severitytext', 'source', 'exposed_countries', 'exposed_population', 'maximum_wind_speed_kmh', 'maximum_storm_surge_m', 'vulnerability', 'category']

In [505]:
rich_disaster_dataset = pd.concat(
    [
        drought_ml,
        earthquake_ml,
        eruption_ml,
        flood_ml,
        forest_fires_ml,
        tropical_cyclone_ml
    ],
    ignore_index=True,
    sort=False
)

print("Rich dataset shape:", rich_disaster_dataset.shape)

print("\nDisaster type distribution:")
print(rich_disaster_dataset["disaster_type"].value_counts())

print("\nTotal columns:", len(rich_disaster_dataset.columns))

print("\nAll columns:")
print(list(rich_disaster_dataset.columns))

Rich dataset shape: (26173, 38)

Disaster type distribution:
disaster_type
Earthquake          20290
Forest Fire          3051
Flood                2126
Tropical Cyclone      405
Drought               240
Eruption               61
Name: count, dtype: int64

Total columns: 38

All columns:
['description', 'alertlevel', 'alertscore', 'episodealertscore', 'country', 'fromdate', 'todate', 'severity_km2', 'iso3', 'gdacs_id', 'duration_days', 'impact', 'longitude', 'latitude', 'disaster_type', 'episodealertlevel', 'source', 'earthquake_magnitude_m', 'capacity', 'depth_km', 'exposed_population_within_100_km', 'severity', 'exposed_population_30km', 'exposed_population_100km', 'vei', 'population_exposure_index_pei', 'severity_magnitude', 'death', 'displaced', 'severity_ha', 'people_affected', 'severitytext', 'exposed_countries', 'exposed_population', 'maximum_wind_speed_kmh', 'maximum_storm_surge_m', 'vulnerability', 'category']

In [506]:
duplicate_columns = rich_disaster_dataset.columns[
    rich_disaster_dataset.columns.duplicated()
]

print("Duplicate column names:")
print(list(duplicate_columns))

Duplicate column names:
[]

In [507]:
missing_summary = (
    rich_disaster_dataset.isnull()
    .sum()
    .sort_values(ascending=False)
)

print("Missing values by column:")
print(missing_summary)

Missing values by column:
vei                                 26112
population_exposure_index_pei       26112
exposed_population_30km             26112
exposed_population_100km            26112
impact                              25933
severity_km2                        25933
severitytext                        25768
exposed_countries                   25768
maximum_storm_surge_m               25768
vulnerability                       25768
category                            25768
maximum_wind_speed_kmh              25768
exposed_population                  25768
severity                            25707
displaced                           24048
severity_magnitude                  24047
death                               24047
severity_ha                         23122
people_affected                     23122
duration_days                       22882
gdacs_id                            20290
capacity                             5883
exposed_population_within_100_km     5883
earthquake_magnitude_m               5883
depth_km                             5883
episodealertlevel                    3291
source                               3291
country                              2211
iso3                                 1081
description                             0
fromdate                                0
episodealertscore                       0
alertscore                              0
alertlevel                              0
disaster_type                           0
todate                                  0
longitude                               0
latitude                                0
dtype: int64

In [508]:
print(rich_disaster_dataset["alertlevel"].value_counts(dropna=False))

alertlevel
Green     21469
GREEN      3994
Orange      349
ORANGE      197
Red          96
RED          41
green        25
orange        2
Name: count, dtype: int64

In [509]:
rich_disaster_dataset["alertlevel"] = (
    rich_disaster_dataset["alertlevel"]
    .astype(str)
    .str.strip()
    .str.title()
)

print(rich_disaster_dataset["alertlevel"].value_counts())

alertlevel
Green     25488
Orange      548
Red         137
Name: count, dtype: int64

In [510]:
rich_disaster_dataset["fromdate"] = pd.to_datetime(
    rich_disaster_dataset["fromdate"],
    format="mixed",
    errors="coerce"
)

rich_disaster_dataset["todate"] = pd.to_datetime(
    rich_disaster_dataset["todate"],
    format="mixed",
    errors="coerce"
)

rich_disaster_dataset["year"] = rich_disaster_dataset["fromdate"].dt.year
rich_disaster_dataset["month"] = rich_disaster_dataset["fromdate"].dt.month

rich_disaster_dataset["duration_days_calculated"] = (
    rich_disaster_dataset["todate"] -
    rich_disaster_dataset["fromdate"]
).dt.total_seconds() / (24 * 60 * 60)

rich_disaster_dataset["duration_days_calculated"] = (
    rich_disaster_dataset["duration_days_calculated"]
    .clip(lower=0)
    .round(2)
)

print(
    rich_disaster_dataset[
        ["fromdate", "todate", "year", "month", "duration_days_calculated"]
    ].head()
)

    fromdate              todate  year  month  duration_days_calculated
0 2017-07-21 2019-02-09 15:07:00  2017      7                    568.63
1 2017-11-21 2018-09-06 09:57:00  2017     11                    289.41
2 2017-12-21 2018-09-06 09:57:00  2017     12                    259.41
3 2018-02-21 2018-11-24 16:27:00  2018      2                    276.69
4 2018-03-21 2018-09-13 13:57:00  2018      3                    176.58

In [511]:
duration = rich_disaster_dataset["duration_days_calculated"]

print("Missing duration:", duration.isna().sum())
print("Negative duration:", (duration < 0).sum())
print("Zero duration:", (duration == 0).sum())
print("Duration > 365 days:", (duration > 365).sum())

print("\nDuration statistics:")
print(duration.describe().round(2))

Missing duration: 0
Negative duration: 0
Zero duration: 20651
Duration > 365 days: 43

Duration statistics:
count    26173.00
mean         4.69
std         28.49
min          0.00
25%          0.00
50%          0.00
75%          0.00
max       1056.00
Name: duration_days_calculated, dtype: float64

In [512]:
negative_episode_scores = (
    rich_disaster_dataset["episodealertscore"] < 0
).sum()

print("Negative episodealertscore values:", negative_episode_scores)

rich_disaster_dataset.loc[
    rich_disaster_dataset["episodealertscore"] < 0,
    "episodealertscore"
] = np.nan

print(
    "Missing episodealertscore after cleaning:",
    rich_disaster_dataset["episodealertscore"].isna().sum()
)

Negative episodealertscore values: 916
Missing episodealertscore after cleaning: 916

In [513]:
candidate_features = [
    "alertlevel",
    "alertscore",
    "episodealertscore",
    "longitude",
    "latitude",
    "year",
    "month",
    "duration_days_calculated"
]

ml_dataset = rich_disaster_dataset[
    candidate_features + ["disaster_type"]
].copy()

print("ML dataset shape:", ml_dataset.shape)

print("\nColumns:")
print(list(ml_dataset.columns))

print("\nMissing values:")
print(ml_dataset.isnull().sum())

ML dataset shape: (26173, 9)

Columns:
['alertlevel', 'alertscore', 'episodealertscore', 'longitude', 'latitude', 'year', 'month', 'duration_days_calculated', 'disaster_type']

Missing values:
alertlevel                    0
alertscore                    0
episodealertscore           916
longitude                     0
latitude                      0
year                          0
month                         0
duration_days_calculated      0
disaster_type                 0
dtype: int64

In [514]:
X = ml_dataset.drop(columns=["disaster_type"])
y = ml_dataset["disaster_type"]

print("X shape:", X.shape)
print("y shape:", y.shape)

print("\nTarget classes:")
print(y.unique())

print("\nClass distribution:")
print(y.value_counts())

print("\nClass percentages:")
print(
    (y.value_counts(normalize=True) * 100)
    .round(2)
)

X shape: (26173, 8)
y shape: (26173,)

Target classes:
<StringArray>
['Drought', 'Earthquake', 'Eruption', 'Flood', 'Forest Fire',
 'Tropical Cyclone']
Length: 6, dtype: str

Class distribution:
disaster_type
Earthquake          20290
Forest Fire          3051
Flood                2126
Tropical Cyclone      405
Drought               240
Eruption               61
Name: count, dtype: int64

Class percentages:
disaster_type
Earthquake          77.52
Forest Fire         11.66
Flood                8.12
Tropical Cyclone     1.55
Drought              0.92
Eruption             0.23
Name: proportion, dtype: float64

In [515]:
from sklearn.model_selection import train_test_split

feature_columns = [
    "alertlevel",
    "alertscore",
    "episodealertscore",
    "longitude",
    "latitude",
    "year",
    "month",
    "duration_days_calculated",
]

X = rich_disaster_dataset[feature_columns].copy()
y = rich_disaster_dataset["disaster_type"].copy()

# Confirm the target is valid
assert X.shape[0] == y.shape[0]
assert y.notna().all()
assert "disaster_type" not in X.columns

print("X shape:", X.shape)
print("y shape:", y.shape)
print("Missing values in X:")
print(X.isnull().sum())
print("Target distribution:")
print(y.value_counts())

X shape: (26173, 8)
y shape: (26173,)
Missing values in X:
alertlevel                    0
alertscore                    0
episodealertscore           916
longitude                     0
latitude                      0
year                          0
month                         0
duration_days_calculated      0
dtype: int64
Target distribution:
disaster_type
Earthquake          20290
Forest Fire          3051
Flood                2126
Tropical Cyclone      405
Drought               240
Eruption               61
Name: count, dtype: int64

In [516]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y,
)

print("X_train:", X_train.shape)
print("X_test:", X_test.shape)
print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

X_train: (20938, 8)
X_test: (5235, 8)
y_train: (20938,)
y_test: (5235,)

In [517]:
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler

numeric_features = [
    "alertscore",
    "episodealertscore",
    "longitude",
    "latitude",
    "year",
    "month",
    "duration_days_calculated",
]

categorical_features = ["alertlevel"]

numeric_pipeline = Pipeline(
    steps=[
        ("imputer", SimpleImputer(strategy="median")),
        ("scaler", StandardScaler()),
    ]
)

categorical_pipeline = Pipeline(
    steps=[
        ("imputer", SimpleImputer(strategy="most_frequent")),
        ("encoder", OneHotEncoder(handle_unknown="ignore")),
    ]
)

preprocessor = ColumnTransformer(
    transformers=[
        ("numeric", numeric_pipeline, numeric_features),
        ("categorical", categorical_pipeline, categorical_features),
    ]
)

In [518]:
X_train_processed = preprocessor.fit_transform(X_train)
X_test_processed = preprocessor.transform(X_test)

print("Processed X_train shape:", X_train_processed.shape)
print("Processed X_test shape:", X_test_processed.shape)

assert X_train_processed.shape[0] == X_train.shape[0]
assert X_test_processed.shape[0] == X_test.shape[0]
assert not pd.isna(X_train_processed).any()
assert not pd.isna(X_test_processed).any()

print("Preprocessing completed successfully.")

Processed X_train shape: (20938, 10)
Processed X_test shape: (5235, 10)
Preprocessing completed successfully.